### ISSUE TITLE
When setting memory and cpu, config needs also to be applied to initContainers

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#1221]
[kind/bug]
Container default request and limits LimitRange applies to every container created.
If you have a LimitRange that sets default container memory of 1 GB but you create your component with 512MB with `odo` it will still compute as a 1GB pod, as the memory the pod needs to run is the highest of the memories of the container and the initContainers. 

Memory and cpu settings need to be applied to the initContainers as well.

How to test:

Create a LimitRange:
```
oc create -f - <<EOF
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: resource-limits
  spec:
    limits:
    - default:
        cpu: 2
        memory: 1.5Gi
      defaultRequest:
        cpu: 400m
        memory: 512Mi
      max:
        memory: 6Gi
      min:
        memory: 10Mi
      type: Container
    - max:
        memory: 12Gi
      min:
        memory: 6Mi
      type: Pod
EOF
```

Create a Quota:
```
oc create -f - <<EOF
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
  scopes:
  - NotTerminating
status:
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
  used:
    limits.cpu: "2"
    limits.memory: 1536Mi
EOF
```

Create a pod with 512 MB memory
```
odo create nodejs frontend --memory 512Mi
```

Check on the Resources/Quota page on the UI, you will see this:

![image](https://user-images.githubusercontent.com/78350/51502645-3e2fb980-1dd7-11e9-9afa-7c370ba19dc1.png)

While, when you set the memory as well on the initContainers, you see:
![image](https://user-images.githubusercontent.com/78350/51502682-691a0d80-1dd7-11e9-87dc-2178bf2c07f2.png)

While redeploying (only +512MB) as it's a rolling deployment, and then, once the redeployment has finished, you see this:
![image](https://user-images.githubusercontent.com/78350/51502710-86e77280-1dd7-11e9-95e9-6bce29e0bacf.png)
