### ISSUE TITLE
Use subPath `ODO_S2I_DEPLOYMENT_DIR`

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1471]
We are using `ODO_S2I_DEPLOYMENT_DIR` to backup artifacts that were built in java based s2i builder image and then restore it the run script.

We can completely avoid this step, and instead, just add volume to `ODO_S2I_DEPLOYMENT_DIR`. To avoid creating another PVC, we can reuse the same one that we already use for app-root, and just use directory in the volume.

Something like this?
```yaml
volumeMounts:
  - name: app-root
    mountPath: /opt/app-root
    subPath: app-root
  - name: deployment-dir
    mountPath: <$ODO_S2I_DEPLOYMENT_DIR>
    subPath: deployment-dir
```
