### ISSUE TITLE
`odo create' overwrites .odo configuration without warning

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#1544]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows 10
- Output of `odo version`: build from master

## How did you run odo exactly?
```
>dist\bin\windows-amd64\odo.exe create nodejs nodejs-test1 --app new --project myproject --context C:\Temp\nodejs-ex\nodejs-ex
 V  Checking component
 V  Checking component version
Please use `odo push` command to create the component with source deployed
```
.odo/config.yaml content is

``` yaml
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: C:\Temp\nodejs-ex\nodejs-ex
  SourceType: local
  Application: new
  Project: myproject
  Name: nodejs-test1
```

```
>dist\bin\windows-amd64\odo.exe create nodejs nodejs-test2 --app new1 --project myproject1 --context C:\Temp\nodejs-ex\nodejs-ex
 V  Checking component
 V  Checking component version
Please use `odo push` command to create the component with source deployed
```

.odo/config.yaml content was updated without warning with new values

``` yaml
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: C:\Temp\nodejs-ex\nodejs-ex
  SourceType: local
  Application: new1
  Project: myproject1
  Name: nodejs-test2
```

## Actual behavior
No warnings about creating new component over existing one

## Expected behavior
Warning about current configuration for context is coing to be replaced with new one

## Any logs, error output, etc?
N/A
