### ISSUE TITLE
link is removed after `odo push`

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1596]
```
▶ git clone https://github.com/marekjelen/katacoda-odo-backend
▶ cd katacoda-odo-backend
▶ odo create wildfly backend --app myapp
▶ odo url create --port 8080
▶ odo push

▶ git clone https://github.com/marekjelen/katacoda-odo-frontend
▶ cd katacoda-odo-frontend
▶ odo create php frontend --app myapp
▶ odo url create --port 8080
▶ odo push


▶ odo link backend
 ✓  Component backend has been successfully linked from the component frontend
```

go to frontend url -> counter is working

verification that secret is added to DC
```
▶ oc get pods frontend-katacoda-odo-igad-2-425jh  -o yaml | grep -A 2 envFrom
    envFrom:
    - secretRef:
        name: backend-katacoda-odo-igad-8080
```

pushing frontend again 
```
▶ odo push
```

go to frontend url -> counter is BROKEN

verification that secret is added to DC

```
▶ oc get pods frontend-katacoda-odo-igad-3-njtbb  -o yaml | grep -A 2 envFrom
```
envFrom disappeared

the same thing happens with links to services 

/cc @syamgk
