### ISSUE TITLE
odo component fails when anyuid is set

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1623]
### UPDATE 2019-04-17
see https://github.com/openshift/odo/issues/1623#issuecomment-484110785

### Original issue description
I'm unable to create component due to failure in one of the iniContainer (copy-files-to-volume)

~~The strange part is that this is not consistent it is happening only sometimes.~~
Update: Now I'm getting this every time on OpenShift 4.0 cluster

```
▶ odo push
 ✓  Checking component
 ✓  Checking component version
 ✓  Creating java component with name java-bayi
 ✓  Initializing 'java-bayi' component
 ✓  Creating component java-bayi
 ✓  Successfully created component java-bayi
 ✓  Applying component settings to component: java-bayi
 ✓  Checking URL java-bayi-8080
 ✓  Successfully created URL for component: java-bayi
 ✓  http://java-bayi-8080-spring-boot-kvcm-default.apps.tkral.devcluster.openshift.com
 ✓  The component java-bayi was updated successfully
 ✓  Successfully updated component with name: java-bayi
 ✓  Pushing changes to component: java-bayi of type binary
 ✗  Waiting for component to start
 ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=java-bayi-spring-boot-kvcm'


▶ oc get pods
NAME                                  READY   STATUS                  RESTARTS   AGE
java-bayi-spring-boot-kvcm-1-cz86r    0/1     Init:CrashLoopBackOff   4          2m34s
java-bayi-spring-boot-kvcm-1-deploy   1/1     Running                 0          2m44s


▶ oc logs java-bayi-spring-boot-kvcm-1-cz86r -c copy-files-to-volume
mkdir: cannot create directory '/mnt/app-root.setup-volume': Permission denied
tar: /opt/app-root: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
mv: cannot stat '/mnt/app-root.setup-volume': No such file or directory

```

I'm able to observe this only on OpenShift 4.0.
Haven't noticed this error last week :-(

**Comment by kadel** [comment]
inside initContainer:
```
[jboss@java-bayi-spring-boot-kvcm-2-kmz7v ~]$ mount | grep mnt
/dev/xvdbx on /mnt type ext4 (rw,relatime,seclabel)

[jboss@java-bayi-spring-boot-kvcm-2-kmz7v ~]$ touch /mnt/.asdf
touch: cannot touch '/mnt/.asdf': Permission denied

[jboss@java-bayi-spring-boot-kvcm-2-kmz7v ~]$ ls -lah /mnt/
total 20K
drwxr-xr-x. 3 root root 4.0K Apr 15 15:19 .
drwxr-xr-x. 1 root root   17 Apr 15 15:28 ..
drwx------. 2 root root  16K Apr 15 15:19 lost+found


```

**Comment by kadel** [comment]
It looks like that  OpenShiftCI is failing for the same reason

**Comment by kadel** [comment]
Versions where it fails and where it works ok:

https://docs.google.com/document/d/1WUj_P2EY-xmDgTMcWwECMW7KnqvkCgR-wF-PDG5vayg/edit#heading=h.tz670zht39n

**Comment by kadel** [comment]
I was able to reproduce this again today using odo build from last week (6799c8a7183887469838a2d36f83158772a72b9f) and current master (d7f528ce15e56bcc2463ed8152dd0449ba4aa4ae) on OpenShift cluster created by installer (v0.16.1) 
(`Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4+0ba401e", GitCommit:"0ba401e", GitTreeState:"clean", BuildDate:"2019-03-31T22:28:12Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`)

**Comment by amitkrout** [comment]
> Versions where it fails and where it works ok:
> 
> https://docs.google.com/document/d/1WUj_P2EY-xmDgTMcWwECMW7KnqvkCgR-wF-PDG5vayg/edit#heading=h.tz670zht39n

Asking for permission. Can you please add the information directly in the comment instead of gdoc.

**Comment by amitkrout** [comment]
I am successfully push java component on OpenShift cluster created by installer [0.16.1](https://github.com/openshift/installer/releases/tag/v0.16.1) and odo binary from master
```
$ oc version
Client Version: version.Info{Major:"4", Minor:"0+", GitVersion:"v4.0.22", GitCommit:"219bbe2f0c", GitTreeState:"", BuildDate:"2019-03-10T22:23:11Z", GoVersion:"", Compiler:"", Platform:""}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4+8156b0c", GitCommit:"8156b0c", GitTreeState:"clean", BuildDate:"2019-03-22T10:37:27Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
```
$ odo create java
 ✓  Checking component
 ✓  Checking component version
Please use `odo push` command to create the component with source deployed
```
```
Amits-MacBook-Pro:test amit$ odo push
 ✓  Checking component
 ✓  Checking component version
 ✓  Creating java component with name java-ntms
 ✓  Initializing 'java-ntms' component
 ✓  Creating component java-ntms
 ✓  Successfully created component java-ntms
 ✓  Applying component settings to component: java-ntms
 ✓  The component java-ntms was updated successfully
 ✓  Successfully updated component with name: java-ntms
 ✓  Pushing changes to component: java-ntms of type local
 ✓  Waiting for component to start
 ✓  Copying files to component
 ✓  Building component
 ✓  Changes successfully pushed to component: java-ntms
Amits-MacBook-Pro:test amit$
```

**Comment by kadel** [comment]
@amitkrout notice that we both used installer v0.16.1 but our Server versions are different.
Yours is `v1.12.4+8156b0c` (from `2019-03-22T10:37:27Z`)
myne is `v1.12.4+0ba401e` (from  `2019-03-31T22:28:12Z`)

**Comment by kadel** [comment]
It looks like the issue is that the volume mount is writable only for root user.
If I use a different image that uses root user (like `busybox`), everything is ok. But once the container uses different users (java s2i image uses `jboss`) it fails.

Simple test to reproduce it:

test.yaml:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: mydc
spec:
  replicas: 1
  selector:
    deploymentconfig: mydc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentconfig: mydc
    spec:
      containers:
      - name: centos
        command:
         - "sleep"
         - "3600"
        image: "registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift"
        volumeMounts:
        - mountPath: /mnt
          name: myvolume
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: mypvc
```
```
oc apply -f test.yaml
```

```
 oc exec -it $(oc get pods -l deploymentconfig=mydc -o jsonpath='{.items[0].metadata.name}') touch /mnt/asdf
```


If you replace `"registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift"` with `"busboy"` everything works

**Comment by kadel** [comment]
It is **NOT** related to the OpenShift cluster version.
It **IS** related to whateve `anyuid` security context`.

### Fails if OpenShift user is allowed to run containers in `anyuid` security context.

Java S2I image uses [`jboss`](https://github.com/jboss-openshift/cct_module/blob/master/jboss/container/user/configure.sh#L8) as a user inside the container.

When container is allowed to run in `anyuid` security context the user will be `jboss`.
```
$ id
uid=185(jboss) gid=0(root) groups=0(root),185(jboss)
```
Probelm is that that OpenShift mouns the volume with  `root:root` as owner. `jboss` user can't write to the directory.
```
$ touch /mnt/asdf
touch: cannot touch '/mnt/asdf': Permission denied

$ ls -lha /mnt/
total 20K
drwxr-xr-x. 3 root root 4.0K Apr 17 13:17 .
drwxr-xr-x. 1 root root    6 Apr 17 13:20 ..
drwx------. 2 root root  16K Apr 17 13:01 lost+found

```

###  Everything is OK if OpenShift user is not allowed to run in `anyuid` security context

Even tho S2I image uses `jboss` user, OpenShift will execute the container with random uid.

```
$ id
uid=1000470000 gid=0(root) groups=0(root),1000470000
```
In this case the volume is mounted with the the same group as the assigned user. So there is no problem with accesssing the volume.
```
$ ls -lah /mnt/
total 20K
drwxrwsr-x. 3 root 1000470000 4.0K Apr 17 14:09 .
drwxr-xr-x. 1 root root          6 Apr 17 14:09 ..
drwxrwS---. 2 root 1000470000  16K Apr 17 14:09 lost+found

$ touch  /mnt/asdf

$ ls -lah /mnt/
total 20K
drwxrwsr-x. 3 root       1000470000 4.0K Apr 17 14:20 .
drwxr-xr-x. 1 root       root          6 Apr 17 14:09 ..
-rw-r--r--. 1 1000470000 1000470000    0 Apr 17 14:20 asdf
drwxrwS---. 2 root       1000470000  16K Apr 17 14:09 lost+found
```

**Comment by kadel** [comment]
Using latest OpenShift ocp build from `4.0.0-0.ci-2019-04-18-041816`  it looks like that `anyuid` is disabled by default and everything works

**Comment by girishramnani** [comment]
so do you think @kadel there is a fix for this issue other then not using the `default` project?

**Comment by jichenjc** [comment]
@girishramnani @kadel could you please help me to understand the anyuid you are talking about above? I hit exactly same issue 

```
[root@infnod-1 ~]# crictl logs de362d1671952
mkdir: cannot create directory '/mnt/app-root.setup-volume': Permission denied
tar: /mnt/app-root.setup-volume: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat '/mnt/app-root.setup-volume': No such file or directory
```

but I already switched to a normal user I created and only have `edit` policy authorized
so it should not have anyuid policy ,I still seeing this error 

can I know how I can verify my ID have this kind of policy? I tried several times with `default` project and `myproject` project, and `admin`, `developer` user as a matrix but none combination works for me 

thanks a lot

**Comment by jichenjc** [comment]
so I don't know how to 
```
Everything is OK if OpenShift user is not allowed to run in anyuid security context
```

**Comment by jichenjc** [comment]
see following output in 

oc edit pod ubi-frontend-qdyr-app-1-wqmp4

which is in 
following status..

Warning  BackOff    17s (x10 over 106s)  kubelet, infnod-1.ocp-test.redhat.com  Back-off restarting failed container


```
initContainers:
  - args:
    - "\nSRC=/opt/app-root\nDEST=/mnt/app-root\n\nif [ -f $DEST/.delete-volume ];
      then\n    rm -rf $DEST\nfi\n if [ -d $DEST ]; then\n    if [ -f $DEST/.sync-volume
      ]; then\n        if ! [[ \"$JUPYTER_SYNC_VOLUME\" =~ ^(false|no|n|0)$ ]]; then\n
      \           JUPYTER_SYNC_VOLUME=yes\n        fi\n    fi\n     if [[ \"$JUPYTER_SYNC_VOLUME\"
      =~ ^(true|yes|y|1)$ ]]; then\n        rsync -ar --ignore-existing $SRC/. $DEST\n
      \   fi\n     exit\nfi\n if [ -d $DEST.setup-volume ]; then\n    rm -rf $DEST.setup-volume\nfi\n\nmkdir
      -p $DEST.setup-volume\ntar -C $SRC -cf - . | tar -C $DEST.setup-volume -xvf
      -\nmv $DEST.setup-volume $DEST\n\t\t\t"
    command:
    - sh
    - -c
    image: image-registry.openshift-image-registry.svc:5000/openshift/ubi@sha256:585573267ba2c624e95210fb0329d0537f9d9a17b4f640c8b48c39c4b3957a97
    imagePullPolicy: IfNotPresent
    name: copy-files-to-volume
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000580000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt
      name: ubi-frontend-qdyr-app-s2idata
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-fnq6d
      readOnly: true
```
