### ISSUE TITLE
deployment gets stuck during updating from local to git in second push

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#1686]
[kind/bug]

How to test

1. `odo create nodejs `
2. `odo push`
3. `odo config set sourcetype git -f`
4. `odo config set sourcelocation https://github.com/sclorg/nodejs-ex -f`
5. `odo push` (gets stuck here)
```
[mrinaldas@localhost nodejs-3.5]$ odo push
 ✓  Checking component
 ✓  Checking component version
 ◑  Applying component settings to component: nodejs-vsgo
```

Reason
```
Failed to pull image "nodejs-vsgo-app:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for nodejs-vsgo-app, repository does not exist or may require 'docker login'
```

**Comment by mik-dass** [comment]
Some more logs by running `oc get dc <dc-name> -o yaml` and selecting the trigger part during the first part
```
 triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nodejs-qylc-app
      - copy-files-to-volume
      from:
        kind: ImageStreamTag
        name: nodejs:latest
        namespace: openshift
      lastTriggeredImage: 172.30.1.1:5000/openshift/nodejs@sha256:fec7b8c5bd9ced07e82345e27aaaa859a43470c71d563ea4c3ffb99c21908715
    type: ImageChange
``` 
and after the update
```
triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nodejs-qylc-app
      from:
        kind: ImageStreamTag
        name: nodejs-qylc-app:latest
        namespace: myproject-1
    type: ImageChange
```
