### ISSUE TITLE
odo project delete considers .odo/config.yaml over the cli args

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1715]
[kind/bug]

odo considers the `.odo/config.yaml`'s project over the one provided as an are to 
`odo project delete <project-name>`

## What versions of software are you using?
- Operating System: fedora 29
- Output of `odo version`:
```
odo v1.0.0-beta1 (1af22f3b)

Server: https://api.engint.openshift.com:443
OpenShift: v3.11.43
Kubernetes: v1.11.0+d4cacc0
```
## How did you run odo exactly?
```
odo project delete prj
```
if I try to delete a project `prj` from a directory with .odo dir then it doesn't delete the `prj` project but rather tries to delete the actual project from the .odo.
 
and if I go to a non .odo dir then it deletes the `prj` project.

**Comment by dharmit** [comment]
On similar lines, `odo project set` doesn't work as expected either:
```bash
$ odo project get
The current project is: myproject

$ odo project list
ACTIVE     NAME
           helloworld
*          myproject

$ odo project set helloworld
Switched to project : helloworld

$ odo project get
The current project is: myproject

$ cd ..

$ odo project get
The current project is: helloworld
```

**Comment by dharmit** [comment]
Project deletion issue mentioned in https://github.com/openshift/odo/issues/1715#issue-442604070 is not reproducible at my side. I'm trying out the steps on CentOS system with below versions of `odo` and `oc`:
```bash
$ odo version
odo v1.0.0-beta1 (e5b00a3)

Server: https://192.168.42.121:8443
Kubernetes: v1.11.0+d4cacc0

$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

Steps tried by me:
```bash
$ cat .odo/config.yaml 
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: python
  SourceLocation: ./
  SourceType: local
  Application: app
  Project: myproject
  Name: python-foel
  Url:
  - Name: python-foel-8080
    Port: 8080

$ odo project list
ACTIVE     NAME
*          myproject
           newproject
           newprojet

$ odo project delete newproject
? Are you sure you want to delete project newproject Yes
 ✓  Deleting project newproject
Deleted project : newproject

$ odo project list
ACTIVE     NAME
*          myproject
           newprojet
```

**Comment by cdrage** [comment]
Did you want to take this up @dharmit ? If not, I can have a look at it :+1:

**Comment by dharmit** [comment]
@cdrage yes I did but wanted to reproduce the issue first. I can self-assign it so that it doesn't show up as unassigned

**Comment by dharmit** [comment]
This is still not reproducible @girishramnani 

```sh
$ odo config view
ENVIRONMENT VARIABLES
------------------------------------------------
NAME    VALUE
FOO     BAZ

COMPONENT SETTINGS
------------------------------------------------
PARAMETER         CURRENT_VALUE
Type              nodejs
Application       app
Project           myproject
SourceType        local
Ref               
SourceLocation    ./
Ports             
Name              nodejs-wmea
MinMemory         
MaxMemory         
Ignore            
MinCPU            
MaxCPU            

$ odo project create newproject
 ✓  New project created and now using project : newproject

$ odo project list
ACTIVE     NAME
*          myproject
           newproject

$ odo project delete newproject
? Are you sure you want to delete project newproject Yes
 ✓  Deleting project newproject [6s]
Deleted project : newproject

$ odo project list
ACTIVE     NAME
*          myproject
```

**Comment by cdrage** [comment]
Ping @girishramnani maybe we can close this.

**Comment by kadel** [comment]
Unable to reproduce, it works as it supposed to 
```
▶ cat .odo/config.yaml
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: ./
  SourceType: local
  Application: app
  Project: myproject
  Name: mynode
  Envs:
  - Name: FOO
    Value: BAR
  Url:
  - Name: mynode-8080
    Port: 8080

tmp/odo-examples/nodejs-ex  master ✗                                                                             266d ⚑ ◒
▶ odo project delete asdf
? Are you sure you want to delete project asdf Yes
 ✓  Deleting project asdf [6s]
Deleted project : asdf
```
