### ISSUE TITLE
odo should support git context directories

### ISSUE THREAD

**Issue by VeerMuchandi** [openshift/odo#2064]
[kind/Enhancement]

## Which functionality do you think we should update/improve?
odo currently doesn't have an option to supply a subdirectory in a git repo.
Look at the snippet from an openshift build configuration 
```
  source:
    contextDir: /todolist-jdbc
    git:
      uri: https://github.com/VeerMuchandi/todolist-java
    type: Git
```
Here `todolist-jdbc` is a subdirectory under the git repo. Currently there is no way to do this with odo. I had to use `oc` or webconsole to create this bc.

## Why is this needed? 
This is minimum functionality expected as we have ( and customers would have) many repositories with subdirectories.
