### ISSUE TITLE
Sharing volumes across components in a Devfile

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#2510]
[kind/Feature]

## Which functionality do you think we should add?
Taking a look at a Spring devfile for example - https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-web-spring/devfile.yaml, devfile components of type `dockerImage` have `volumes`:
```
  -
    type: dockerimage
    alias: tools
    image: quay.io/eclipse/che-java8-maven:nightly
    env:
      - name: MAVEN_CONFIG
        value: ""
      - name: JAVA_OPTS
        value: "-XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
          -Duser.home=/home/user"
      - name: MAVEN_OPTS
        value: $(JAVA_OPTS)
    memoryLimit: 768Mi
    endpoints:
      - name: '8080/tcp'
        port: 8080
    mountSources: true
    volumes:
      - name: m2
        containerPath: /home/user/.m2
```

If multiple devfile `dockerImage` components mention the same volume `name`(`containerPath` can be different since they're mounted on the component's container), the devfile components should share the same volume.

The Volumes Name property in the Devfile schema also seems to mention this https://github.com/redhat-developer/devfile/blob/master/docs/devfile.json#L496
```
"properties": {
    "name": {
        "type": "string",
        "title": "The Volume Name",
        "description": "The volume name. If several components mount the same volume then they will reuse the volume and will be able to access to the same files",
        "examples": [
            "my-data"
        ]
    },
    "containerPath": {
        "type": "string",
        "title": "The path where volume should be mount to container",
        "examples": [
            "/home/user/data"
        ]
    }
}
```

## Why is this needed?
When working with issue https://github.com/openshift/odo/issues/2472 for Devfile Volume support, it made sense for multiple devfile components to share volumes if they mention the same name.
