### ISSUE TITLE
odo push  trigger redeploy even if there are no changes in devfile

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2662]
/kind bug
/area devfile
/priority medium

If there are no changes to Devfile.yaml that would resolve in changes in Deploment the Deployment should not be triggered.

Current behaviour
```
export ODO_EXPERIMENTAL=true
# running push for the first time
▶ odo push ; kubectl get pods
 •  Push devfile component odo-examples  ...
 ✓  Waiting for component to start [9s]
 ✓  Push devfile component odo-examples [10s]
NAME                           READY   STATUS    RESTARTS   AGE
odo-examples-8cb546c7b-sbmxd   1/1     Running   0          11s


# just triggering push again without any changes

▶ odo push ; kubectl get pods
 •  Push devfile component odo-examples  ...
 ✓  Waiting for component to start [174ms]
 ✓  Push devfile component odo-examples [1s]
NAME                           READY   STATUS        RESTARTS   AGE
odo-examples-8cb546c7b-sbmxd   1/1     Terminating   0          71s
```

**Comment by rajivnathan** [comment]
@cdrage I was wondering why I couldn't reproduce it but others could. We figured out that it has to do with ordering of things in the deployment spec when there is more than a single item in an array. In my case I had a devfile with only a single volume but others were reproducing the problem with devfiles that had two volumes.

For example, I cannot reproduce this problem with this devfile:
```
apiVersion: 1.0.0
metadata:
  generateName: openLiberty
attributes:
  odo.autorestart: "false"
projects:
- name: openLiberty
  source:
    type: git
    location: https://github.com/rajivnathan/openLiberty.git
components:
- type: chePlugin
  id: redhat/java/latest
  memoryLimit: 1512Mi
- alias: devruntime
  mountSources: true
  type: dockerimage
  image: jeevandroid/open-liberty-dev:latest
  command: ['tail']
  args: ['-f', '/dev/null']
  memoryLimit: 768Mi
  env:
  - name: test15
    value: test4
  volumes:
  - name: m2
    containerPath: /home/user/.m2
  endpoints:
  - name: 9090/tcp
    port: 9090
commands:
- actions:
  - command: /artifacts/bin/build.sh
    component: devruntime
    type: exec
    workdir: /projects/openLiberty
  name: DevBuild
- actions:
  - command: /artifacts/bin/run.sh
    component: devruntime
    type: exec
    workdir: /projects/openLiberty
  name: DevRun
- actions:
  - command: /artifacts/bin/debug.sh
    component: devruntime
    type: exec
    workdir: /projects/openLiberty
  name: DevDebug
```

But if you just add another volume to the devruntime component you'll most likely see the problem. It doesn't seem to happen if you have multiple environment variables so I'm wondering if it's something to do with how we're parsing the volumes specifically.

**Comment by cdrage** [comment]
@rajivnathan I can't seem to replicate it even with an extra volume with one of the components..

See my below `devfile.yaml`:

```yaml
---
apiVersion: 1.0.0
metadata:
  generateName: openLiberty
projects:
  -
    name: openLiberty
    source:
      type: git
      location: "https://github.com/rajivnathan/openLiberty.git"
components:
  -
    type: chePlugin
    id: redhat/java/latest
    memoryLimit: 1512Mi
  -
    type: dockerimage
    image: jeevandroid/open-liberty-dev:latest
    alias: runtime
    memoryLimit: 768Mi
    command: ['tail']
    args: [ '-f', '/dev/null']
    env:
      - name: "MODE"
        value: "TEST"
      - name: "myprop"
        value: "myval"
    endpoints:
      - name: '9090/tcp'
        port: 9090
    mountSources: true
    volumes:
      - name: m2
        containerPath: /home/user/.m2
      - name: m3
        containerPath: /home/user/.m3
  -
    type: dockerimage
    image: jeevandroid/open-liberty-dev:latest
    alias: build
    memoryLimit: 768Mi
    command: ['tail']
    args: [ '-f', '/dev/null']
    env:
      - name: "MODE2"
        value: "TEST2"
      - name: "myprop2"
        value: "myval2"
    endpoints:
      - name: '9191/tcp'
        port: 9191
    mountSources: true
    volumes:
      - name: m2
        containerPath: /home/user/.m2
commands:
  -
    name: Build
    actions:
      -
        type: exec
        component: runtime
        command: "TEST_ENV=true /artifacts/bin/build.sh"
        workdir: /projects/openLiberty
  -
    name: Run
    actions:
      -
        type: exec
        component: runtime
        command: "/artifacts/bin/run.sh"
        workdir: /projects/openLiberty
```

And when I run it:

```sh
▶ odo push
 •  Push devfile component devfile  ...
 ✓  Checking files for pushing [241560ns]
 ✓  Waiting for component to start [56s]
 ✓  Syncing files to the component [1s]
 ✓  Push devfile component devfile [58s]
 ✓  Changes successfully pushed to component

~/openshift/devfile                                                                                                                                                                                                                                                                                                                                                         
▶ odo push
 •  Push devfile component devfile  ...
 ✓  Checking file changes for pushing [171035ns]
 ✓  No file changes detected, skipping build. Use the '-f' flag to force the build.
 ✓  Push devfile component devfile [526ms]
 ✓  Changes successfully pushed to component
```

This is against the latest master.
