### ISSUE TITLE
Assign labels to service spun up from an operator

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2801]
## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master

## How did you run odo exactly?
`odo service create etcdoperator.v0.9.4 --crd EtcdCluster` to create operator backed service in the experimental mode.

## Actual behavior
Service is spun up but the result OpenShift objects don't have labels like the ones when a service (`ServiceInstance`) is created from Service Catalog

## Expected behavior
Service created from Operators should have labels like:
```
  labels:
    app: app
    app.kubernetes.io/instance: postgresql-persistent
    app.kubernetes.io/managed-by: odo
    app.kubernetes.io/managed-by-version: v1.1.1
    app.kubernetes.io/name: postgresql-persistent
    app.kubernetes.io/part-of: app
```
as with services created from Service Catalog
