### ISSUE TITLE
odo devfile push's run process should depend on devfile odo.restart

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#2820]
/kind user-story

## User Story
Devfile's odo push's restart should depend on `odo.restart: "false"` in the devfile.

## Acceptance Criteria 
- [ ] It should check for the attribute in the devfile when push is executed
- [ ] Make sure odo restart is in the devfile schema 1.0 and 2.0

## Links 
- Feature Request: 
- Related issue: https://github.com/openshift/odo/issues/2654

/kind user-story
/area devfile

**Comment by kadel** [comment]
> * [ ]  Make sure odo restart is in the devfile schema 1.0 and 2.0

We can easily use `attributes` in devfile 1.0 for this.

In the devfile it would look like this:
```
...
...
commands:
  - name: devBuild
    actions:
      - type: exec
        component: tools
        command: "ls -lah"
        workdir: "$MYDIR"
  - name: devRun
    attributes:
        restart: false
    actions:
      - type: exec
        component: tools
        command: "mvn springboot:run"
```

Odo checks for `restart` field in attributes for `devRun` command and if it is `true` it woun't try to restart the run process.
Odo should always try to start it (`supervisord ctl start devrun`) just to make sure that it is running, as the process might fail due to some error, than the user will just be able to do `odo push` to start it again.
