### ISSUE TITLE
"odo create" supports for dowloading devfile compoent template

### ISSUE THREAD

**Issue by GeekArthur** [openshift/odo#2850]
/kind user-story

## User Story
As a user I want to use the template that is compatible with the devfile I specify during `odo create [component type]` so that I don't need to bring my own template and I can start working on the component development based on the provided template.

## Acceptance Criteria 
- [ ] Read the template location directly from devfile and use that template location to download template:
```
projects:
-
  name: example
  source:
    type: git
    location: https://github.com/golang/example.git
  clonePath: src/github.com/golang/example/
```
- [ ] Create a new flag like `--template` to enable the feature of downloading template

That's my initial thought and rough idea 🤔 , please feel free to add comments or questions

/kind user-story
/area devfile
