### ISSUE TITLE
odo should automatically create url for previewUrl

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2858]
/kind user-story

## User Story
As a user I want to just run `odo push` after cloning project with devfile.yaml in the project root and have the project running and accessible in the cluster, without executing any other command.

## Acceptance Criteria 
- [ ] `odo push` should automatically create URL for any [`previewUrl`](https://github.com/redhat-developer/devfile/blob/master/docs/devfile.md#previewur) defined in devfile.yaml
- [ ] Url should be by default represented by Route on OpenShift and by Ingress on Kuberenetes (https://github.com/openshift/odo/issues/2727)
- [ ] `odo push` against k8s cluster with devfile that has `previewUrl` should show a warning listing all previewUrl ports and inform user that she/he needs to use `odo url create` command to specify host for URL
- [ ] `odo push --ignorePreviewUrl` should ignore all `previewUrl` in the devfile. No Ingress or Route will be auto-created based on the `previewUrl`s in devfile.yaml

## Notes
PreviewUrl documentation https://github.com/redhat-developer/devfile/blob/master/docs/devfile.md#previewurl

- This might be possible just for OpenShift, and for Kubernetes, the Ingress host might be required.
- What to do for Kubernetes than?
    - Options:
        - ~~fail and tell the user to run `odo url create --port 9080 --host mycluster.example.com` ?~~
        - ignore preview and tell user to run `odo url create` with `--host` to create url?

Example:
For the following devfile, `odo push` should automatically create URL for port 9080 

```yaml
apiVersion: 1.0.0
metadata:
  generateName: openLiberty
attributes:
  odo.autorestart: "false"
projects:
  - name: openLiberty
    source:
      type: git
      location: https://github.com/rajivnathan/openLiberty.git
components:
  - alias: devruntime
    mountSources: true
    type: dockerimage
    image: jeevandroid/open-liberty-dev:latest
    memoryLimit: 768Mi
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    endpoints:
      - name: 9080/tcp
        port: 9080
      - name: 9443/tcp
        port: 9443
commands:
  - actions:
      - command: /artifacts/bin/build.sh
        component: devruntime
        type: exec
        workdir: /projects/openLiberty
    name: devBuild
  - name: devRun
    previewUrl:
      port: 9080
      path: /
    actions:
      - type: exec
        command: /artifacts/bin/run.sh
        component: devruntime
        workdir: /projects/openLiberty
```
/kind user-story
/area OpenShift
/area url
/area devfile
/priority medium
