### ISSUE TITLE
Test flake comming due no check is added for operator (etcd) responsiveness

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2943]
/kind bug

## What versions of software are you using?

**Operating System:**
supported
**Output of `odo version`:**
master
## How did you run odo exactly?
```
make configure-installer-tests-cluster
make test-operator-hub
```

## Actual behavior
```
Running odo with args [odo project set ci-operator-hub-project]
[odo] Switched to project : ci-operator-hub-project
Running odo with args [odo catalog list services]
[odo] Operators available in the cluster
[odo] NAME                          CRDs
[odo] mongodb-enterprise.v1.4.5     MongoDB, MongoDBUser, MongoDBOpsManager



Running odo with args [odo service create  --crd EtcdCluster]
[odo]  ✗  Could not find specified operator 
```
etcd operator does not come up properly or failed to install after apply it through ```oc create...``` command. For example
```
oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: etcd
  namespace: ${OPERATOR_HUB_PROJECT}
spec:
  channel: singlenamespace-alpha
  installPlanApproval: Automatic
  name: etcd
  source: community-operators
  sourceNamespace: openshift-marketplace
EOF
``` 
That is why etcd operator is not listed in the catalog list. 

## Expected behavior
So from our end we can write some check to confirm even after applying it through oc create etcd is now responsive and ready for use.
