### ISSUE TITLE
Provide information on the starter projects available to each component

### ISSUE THREAD

**Issue by skoh7645** [openshift/odo#3005]
/kind user-story
/assign
/area devfile

## User Story
As a user, I want odo to be able to list starter projects available to each component, and provide some basic information on each starter project including: 
- Name
- Description (this would need to be added to the devfile v2 schema)

This information would give me a better indication as to which starter project fits my needs.

## Acceptance Criteria 
- [ ] It should provide information for all available starter projects associated with each component
- [ ] This list command will only be run if the following conditions are met:
  - Experimental flag has been enabled
  - The component is a devfile component
  - There is at least one project defined in the devfile of the given component

## Possible Implementations
1. Include a "project" column in the output of `odo catalog list components` with a comma-separated list of available projects for each component by the project name.
2. Allow an argument for the component name in the `odo catalog list components` command, and then only list details of that component and it's projects. Here we could list both the project name and project description. e.g. `odo catalog list components nodejs` would list the available projects for the `nodejs` component.
   - Another flag could also be used here to show all information about the component's projects. 
   - We could also fall to interactive mode if the user does not specify which project they want, but there are multiple projects defined
3. Add a flag `--showProjects` (or another term) to the `odo catalog list components` and that will mean we show project details in the same table.

**Comment by cdrage** [comment]
Hey @skoh7645 here are my thoughts:

With regards to "starter" project information. To be blunt (and just my opinion, please everyone else chime in), but couldn't this be remedied in either an `odo init` command or ample online documentation?

The problem being is no having to rely on a command that we have to maintain consistency on with each new feature of Devfile being implemented. 

For example, when we type just `odo` we have this helpful output:

```sh
▶ odo
(OpenShift Do) odo is a CLI tool for running OpenShift applications in a fast and automated manner.
Reducing the complexity of deployment, odo adds iterative development without the worry of deploying your source code.

Find more information at https://github.com/openshift/odo

Get started by creating a new application:

 git clone https://github.com/openshift/nodejs-ex && cd nodejs-ex
 odo create nodejs
 odo push

Your nodejs application has now been deployed. odo has pushed the source code, built the application and deployed it on OpenShift. 
You can now edit your code in real time and watch as odo automatically deploys your application.

 odo watch

To access your application, create a URL:

 odo url create myurl
 odo push

More information such as logs or what components you've deployed can be accessed with these commands:

 odo describe
 odo list
 odo log

To see a full list of commands, run 'odo --help'
```

Same for `odo create --help`:

```sh
▶ odo create --help
Create a configuration describing a component.

 If a component name is not provided, it'll be auto-generated.

 A full list of component types that can be deployed is available using: 'odo catalog list'

 By default, builder images (component type) will be used from the current namespace. You can explicitly supply a namespace by using: odo create namespace/name:version If version is not specified by default, latest will be chosen as the version.

Usage:
  odo create <component_type> [component_name] [flags]

Examples:
  # Create new Node.js component with the source in current directory.
  odo create nodejs
  
  # Create new Node.js component named 'frontend' with the source in './frontend' directory
  odo create nodejs frontend --context ./frontend
  
  # Create new Java component with binary named sample.jar in './target' directory
  odo create java:8  --binary target/sample.jar
  
  # Create new Node.js component with source from remote git repository
  odo create nodejs --git https://github.com/openshift/nodejs-ex.git
  
  # Create new Node.js component with custom ports, additional environment variables and memory and cpu limits
  odo create nodejs --port 8080,8100/tcp,9100/udp --env key=value,key1=value1 --memory 4Gi --cpu 2
```

In my opinion, instead of implementing "starter project" information into `odo catalog list components`, I would rather improve the current documentation that we lack with regards to what starter projects to use.

If we were to implement this, a user would have to hunt through running `--help` commands before finding the one line that mentions starter projects.

Also, instead of implementing a command, couldn't we add a COLUMN to the `odo catalog list components` output that indicates it's a good starter project?

With regards to your implementation and using `-p`, we already have the command `odo catalog describe` that will output all information with regards to the component / service.

**Comment by johnmcollier** [comment]
@cdrage  Here's my 2 cents:
- I don't think it's feasible to just document the starter projects for each devfile component, especially as the list of supported devfiles in odo grow.
- I'm concerned that adding an additional column for projects to `odo catalog list` would make the output too cluttered (especially if the components has multiple projects available to it).

Now, if we only showed a subset of the project info (like repo or project name) in `odo catalog list`, and kept the full info under `odo catalog describe`, I think I'd be good with that.

**Comment by GeekArthur** [comment]
My concern is that if we add subset of the project info for devfile component we may create terminology confusion for user (given we already displayed `PROJECT` for s2i component) as in the same result page the "Project" points to two definitions respectively:

- Project for s2i component: Similar to namespace in k8s world
- Project for devfile component: It's the project template that is hosted on GitHub or other source host

```
odo catalog list components                                                                                                                                                      ✔  5s   11:26:40 
Odo OpenShift Components:
NAME          PROJECT       TAGS                                        SUPPORTED
nodejs        openshift     10,8,8-RHOAR,latest                         YES
openjdk18     openshift     latest                                      YES
dotnet        openshift     2.0,latest                                  NO
httpd         openshift     2.4,latest                                  NO
nginx         openshift     1.10,1.12,1.8,latest                        NO
nodejs        openshift     6                                           NO
perl          openshift     5.24,5.26,latest                            NO
php           openshift     7.0,7.1,latest                              NO
python        openshift     2.7,3.5,3.6,latest                          NO
ruby          openshift     2.3,2.4,2.5,latest                          NO
wildfly       openshift     10.0,10.1,11.0,12.0,13.0,8.1,9.0,latest     NO

Odo Devfile Components:
NAME                 DESCRIPTION                           SUPPORTED
maven                Upstream Maven and OpenJDK 11         YES
nodejs               Stack with NodeJS 10                  YES
openLiberty          Open Liberty microservice in Java     YES
java-spring-boot     Spring Boot® using Java               YES
```

**Comment by johnmcollier** [comment]
@GeekArthur If we make the clarification that it's a `starter project` or or `template project` that shouldn't be an issue.

**Comment by kadel** [comment]
> @GeekArthur If we make the the column header `starter project(s)` or a `template project(s)` that shouldn't be an issue, especially if that output in the column is a git repo link.

for `odo catalog list components` output
I would actually just output the names of the projects, so the user knows what options are available for `--downloadSource` flag for `odo create`.

Showing details like git repo link should be displayed in `odo catalog describe component <devfile name>`


```
odo catalog list components                                                                                                                                                     Devfile Components:
NAME                 DESCRIPTION                           SUPPORTED       STARTER PROJECTS
maven                Upstream Maven and OpenJDK 11         YES                
nodejs               Stack with NodeJS 10                  YES                nodejs-ex
openLiberty          Open Liberty microservice in Java     YES
java-spring-boot     Spring Boot® using Java               YES                petclinic, other-example




odo catalog describe component java-spring-boot

odo catalog list components                                                                                                                                                     Devfile Components:
NAME                 DESCRIPTION                           SUPPORTED       STARTER PROJECTS
maven                Upstream Maven and OpenJDK 11         YES                
nodejs               Stack with NodeJS 10                  YES                nodejs-ex
openLiberty          Open Liberty microservice in Java     YES
java-spring-boot     Spring Boot® using Java               YES                petclinic, other-example




odo catalog describe component java-spring-boot

apiVersion: 1.0.0
metadata:
  generateName: java-spring-boot
projects:
  - name: petclicnic
    source:
      type: git
      location: "https://github.com/spring-projects/spring-petclinic.git"
  - name: other-example
    source:
      type: git
      location: "https://github.com/other-example/other-example.git"
components:
  - type: dockerimage
    alias: tools
    image: quay.io/eclipse/che-java11-maven:nightly
    memoryLimit: 512Mi
    mountSources: true
    endpoints:
      - name: '8080/tcp'
        port: 8080
    volumes:
      - name: m2
        containerPath: /home/user/.m2
commands:
  - name: devBuild
    actions:
      - type: exec
        component: tools
        command: "mvn package"
  - name: devRun
    actions:
      - type: exec
        component: tools
        command: "java -jar target/*.jar"

```



doing `odo catalog list components nodejs` goes against how `odo catalog list services` and  `odo catalog describe services` work. If we really want `odo catalog list components nodejs` that we will have to implement the same behavior for `odo catalog list services`!
