### ISSUE TITLE
Convert s2i components into devfile

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3156]
/kind user-story

## User Story
As a current odo user, I want to be able to benefit from new features that require devfile without manually recreating my components

## Acceptance Criteria 
- [x]  the conversion command should work on the current directory with the "LocalConfig" component 
- [x] conversion command (`odo utils convert-to-devfile`) should be able to convert the "LocalConfig"  component (`.odo/config.yaml`)  into a devfile component (`devfile.yaml` and `.odo/env/env.yaml`)
- [x] resulting devfile should be in v2 format
- [ ] if possible `odo push` command should be able to update existing Kubernetes resources (`odo utils convert-to-devfile && odo push` should work fine). If this is not possible the output of the conversion command should instruct user to run `odo delete` and `odo push` again to create resources based on new Devfile definition.

/kind user-story

## Background
To make the depreciation of s2i based components easier and quicker we could write a converter that would take old s2i based components and automatically create devfile.yaml for them.

It should be fairly straight forward to create devfile.yaml that uses s2i builder image and executes commands based on the information in s2i builder image.

The conversion command should inspect s2i builder image and based on the obtained information and based on the information in local config it should generate devfile.yaml and env.yaml

<details>
  <summary>Example</summary>

Assuming the nodejs componen with following config.yaml
```yaml
kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: app
  Project: demo
  Name: frontend
```

we could generate something like this:
env.yaml
```yaml
ComponentSettings:
  Name: frontend
  Namespace: demo
```
devfile.yaml
```yaml
schemaVersion: 2.0.0
metadata:
  name: frontend
  version: 1.0.0
components:
  - container:
      name: s2i-builder
      image: registry.redhat.io/rhoar-nodejs/nodejs-10@sha256:74a3ef2964efc03dfc239da3f09691b720ce54ff4bb47588864adb222133f0fc
      mountSources: true
      endpoints:
        - name: "nodejs"
          configuration:
            discoverable: false
            public: true
            protocol: tcp
            scheme: http
          targetPort: 8080
commands:
  - exec:
      id: s2i-assemble
      component: s2i-builder
      commandLine: /opt/odo/bin/assemble-and-restart
      group:
        kind: build
        isDefault: true
  - exec:
      id: s2i-run
      component: s2i-builder
      commandLine: /opt/odo/bin/supervisord ctl start run
      group:
        kind: run
        isDefault: true
```
(haven't tested this)

</details>
