### ISSUE TITLE
Devfile does not create metadata.name but creates metadata.generateName

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#3212]
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** Master branch

## How did you run odo exactly?

```sh
odo create java-spring-boot
```

## Actual behavior

Here is the output: 

```yaml
apiVersion: 1.0.0    
metadata:    
  generateName: java-spring-boot    
projects:    
  -    
    name: springbootproject    
    source:    
      type: git    
      location: "https://github.com/odo-devfiles/springboot-ex.git"    
```

## Expected behavior

Shouldn't we also have `metadata.name` entry too? 

According to https://redhat-developer.github.io/devfile/devfile.html generateName will be used for: `Workspaces created from devfile, will use it as base and append random suffix. It’s used when name is not defined.`

If the user does not provide a name, shouldn't we propagate the `metadata.name` slot too?

## Any logs, error output, etc?

N/A
