### ISSUE TITLE
Inconsistencies in location of project code following `odo push`

### ISSUE THREAD

**Issue by groeges** [openshift/odo#3234]
/kind bug

The location of the project source within the target container changes dependant on whether there is more than 1 project defined in the devfile.yaml.  If the devfile (v1) contains a single project:
```
  projects:
    - name: default
       source:
          type: git
          location: "https://github.com/groeges/java-openliberty-default.git"
```
the once the project has been created `odo create ...` the source from the project is all the the users local directory. Following an `odo push` the source is synced to the container and is put into the `$CHE_PROJECTS_ROOT/default` directory and the env var is set to `CHE_PROJECTS_ROOT=/projects`

However, if there is more than 1 project in the devfile.yaml
```
  projects:
    - name: default
       source:
          type: git
          location: "https://github.com/groeges/java-openliberty-default.git"
    - name: simple
       source:
          type: git
          location: "https://github.com/groeges/java-openliberty-simple.git"
```
then following the `odo push` the project source is synced to the container and is put into the `$CHE_PROJECTS_ROOT` directory and the env var is still set to `CHE_PROJECTS_ROOT=/projects` 

Is this expected? 

If it is, this makes it difficult to write any scripts that the build stage is to use as the location of the source is unknown.

## What versions of software are you using?

**Operating System:**
Mac OS 
**Output of `odo version`:**
odo v1.2.1 (b061f3434)

## How did you run odo exactly?
odo create java-openliberty --registry local --downloadSource
odo url create openliberty-docker-9080 --port 9080 --exposed-port 55555 
odo push --show-log

## Actual behavior
sync location of project source is not consistent

## Expected behavior
consistent location of project source, or env var set to identify the source location.
