### ISSUE TITLE
Throw Error, If multiple commands of same kind specified in devfile v2 and none is default

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3271]
/kind feature

## Which functionality do you think we should add?
Currently for devfile V2, we are allowing users to specify multiple commands of same kind, and selecting the first command from the list, if none of them is default.

We need to throw error for following case _"Multiple build command specified in devfile with no default"_

```
commands:
  - exec:
      id: build the app
      component: tools
      commandLine: "/artifacts/bin/build-container-full.sh"
      workingDir: /projects/springbootproject
      group:
        kind: build
  - exec:
      id: build
      component: runtime
      commandLine: "mvn compile"
      workingDir: /
      group:
        kind: build
```
