### ISSUE TITLE
ODO push doesn't work with volumeMounts for v2

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#3308]
/kind bug

## How did you run odo exactly?

`odo push`

with a V2 devfile with volumeMounts

```
schemaVersion: 2.0.0
metadata:
  name: test-devfile
projects:
  - name: nodejs-web-app
    git:
      location: "https://github.com/che-samples/web-nodejs-sample.git"
components:
  - container:
      name: runtime
      image: quay.io/eclipse/che-nodejs10-ubi:nightly
      memoryLimit: 1024Mi
      env:
        - name: FOO
          value: "bar"
      endpoints:
        - name: "3000/tcp"
          configuration:
            protocol: tcp
            scheme: http
          targetPort: 3000
      mountSources: true
      volumes:
        - name: myvol
          containerPath: /data
  - container:
      name: runtime2
      image: quay.io/eclipse/che-nodejs10-ubi:nightly
      memoryLimit: 1024Mi
      mountSources: false
      volumes:
        - name: myvol
          containerPath: /data
        - name: myvol2
          containerPath: /data2
commands:
  - exec:
      id: devBuild
      component: runtime
      commandLine: "echo hello >> myfile.log"
      workingDir: /data
      group:
        kind: build
        isDefault: true
  - exec:
      id: devRun
      component: runtime2
      commandLine: "cat myfile.log"
      workingDir: /data
      group:
        kind: run
        isDefault: true
```

## Actual behavior

```
 ✗  Executing devBuild command "echo hello >> myfile.log" [82ms]
 ✗  Failed to start component with name nodejs.
Error: Failed to create the component: unable to execute the build command: error while streaming command: command terminated with exit code 1
```

## Expected behavior

`odo push` should not error out.

## Any logs, error output, etc?

While debugging, I found that volumeMounts are not picked up from the V2 devfile while parsing. Thus no volume is created.
