### ISSUE TITLE
"odo create nodejs --downloadSource" and "--starter" creating one extra file on windows platform

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3367]
/kind bug

## What versions of software are you using?

**Operating System:**
win10

**Output of `odo version`:**
master

## How did you run odo exactly?

Ran `make test-cmd-devfile-create` on windows. Also Ran the steps manually.

1. created new context dir with experimental mode enable
2. `odo project create testd` then cd <new context>
3. `odo create nodejs --downloadSource` or `odo create nodejs --downloadSource nodejs-web-app`

## Actual behavior

On Windows 
```
> mkdir -p testano

    Directory: C:\Users\Admin\go\src\github.com\openshift\odo


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6/17/2020   8:05 AM                testano
> odo project create testanother
 V  Project 'testanother' is ready for use
 V  New project created and now using project: testanother

> cd .\testano\

> odo create nodejs --downloadSource
Experimental mode is enabled, use at your own risk

Validation
 V  Checking devfile compatibility [0ns]
 V  Creating a devfile component from registry: DefaultDevfileRegistry [4ms]
 V  Validating devfile component [584800ns]

Please use `odo push` command to create the component with source deployed

> ls


    Directory: C:\Users\Admin\go\src\github.com\openshift\odo\testano


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6/17/2020   8:10 AM                .odo
d-----        6/17/2020   8:10 AM                odo-devfiles-nodejs-ex-39b5ec7
-a----        6/17/2020   8:10 AM            731 devfile.yaml

> ls .\odo-devfiles-nodejs-ex-39b5ec7\


    Directory: C:\Users\Admin\go\src\github.com\openshift\odo\testano\odo-devfiles-nodejs-ex-39b5ec7


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6/17/2020   8:10 AM                app
-a----        6/17/2020   8:10 AM             14 .gitignore
-a----        6/17/2020   8:10 AM          14197 LICENSE
-a----        6/17/2020   8:10 AM          14289 package-lock.json
-a----        6/17/2020   8:10 AM            265 package.json
-a----        6/17/2020   8:10 AM            449 README.md
```

Extra file created here is `odo-devfiles-nodejs-ex-39b5ec7` which leads [`--downloadSource`](https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_create_test.go#L208) and [`--downloadSource=nodejs-web-app`](https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_create_test.go#L228) to fail. All those expected files which are supposed to be under current directory is actually found under `./odo-devfiles-nodejs-ex-39b5ec7` on windows. Really a weird behavior but somehow it is happening.

## Expected behavior

`odo create nodejs --downloadSource` or `--downloadSource=nodejs-web-app` should not create one extra file `odo-devfiles-nodejs-ex-39b5ec7` on windows.

## Any logs, error output, etc?

👀

**Comment by amitkrout** [comment]
> Extra file created here is odo-devfiles-nodejs-ex-39b5ec7 which leads --downloadSource and --downloadSource=nodejs-web-app to fail.

Where is it failing ? is the push failing ? if yes paste the verbose output log. 
 ```PS > odo push -v 4 ```

**Comment by prietyc123** [comment]
> @prietyc123 Where is it failing ? is the push failing ? if yes paste the verbose output log.
PS > odo push -v 4

@amitkrout No, `odo push` is not failing. Its something weird behaviour on windows. Usually, what happens is `odo create nodejs --downloadSource` create the component in the current directory and `package.json` and all the other files will resides under the current directory itself. Whereas on windows somehow `package.json`, `app` etc.. falls under one random directory `./odo-devfiles-nodejs-ex-39b5ec7`. Due to which whatever the [files](https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_create_test.go#L208) we are expecting in the current directory is not available there and this leads to the failure.

Does it answer your question?

**Comment by amitkrout** [comment]
Got it, test script is failing due to this weird behavior on windows platform. ping @EnriqueL8 https://github.com/openshift/odo/issues/3367#issuecomment-645305025

**Comment by prietyc123** [comment]
Same issue I am facing with `--starter` while creating the component on windows. Including `--starter` in the issue heading.

Steps to reproduce:

```
> mkdir -p testcreate


    Directory: C:\Users\Admin\go\src\github.com\openshift\odo


Mode                LastWriteTime         Length Name
----                -------------         ------ ----


> cd .\testcreate\

> odo preference view
PARAMETER             CURRENT_VALUE
UpdateNotification
NamePrefix
Timeout
PushTimeout
Experimental          true
PushTarget

> ls

> odo create nodejs --starter
Experimental mode is enabled, use at your own risk

Validation
 V  Checking devfile existence [88ms]
 V  Checking devfile compatibility [1ms]
 V  Creating a devfile component from registry: DefaultDevfileRegistry [96ms]
 V  Validating devfile component [964700ns]

Please use `odo push` command to create the component with source deployed

> ls


    Directory: C:\Users\Admin\go\src\github.com\openshift\odo\testcreate


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        7/10/2020   7:07 AM                .odo
d-----        7/10/2020   7:07 AM                odo-devfiles-nodejs-ex-e832173
-a----        7/10/2020   7:07 AM              9 .gitignore
-a----        7/10/2020   7:07 AM           1277 devfile.yaml


> cd .\odo-devfiles-nodejs-ex-e832173\

> ls


    Directory: C:\Users\Admin\go\src\github.com\openshift\odo\testcreate\odo-devfiles-nodejs-ex-e832173


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        7/10/2020   7:07 AM                test
-a----        7/10/2020   7:07 AM           1635 .gitignore
-a----        7/10/2020   7:07 AM          14197 LICENSE
-a----        7/10/2020   7:07 AM          18290 package-lock.json
-a----        7/10/2020   7:07 AM            395 package.json
-a----        7/10/2020   7:07 AM           1189 README.md
-a----        7/10/2020   7:07 AM           1903 server.js
```

**Comment by prietyc123** [comment]
We have already set up our periodic job on PSI for fedora, windows and macOS. However the platform specific issues are acting as hindrance for the test run, so IMO its high time we fix these bugs or test script issues. But here good point is we have refractor sprint and I assume we can fix such small issue in that too 🙂

**Comment by mik-dass** [comment]
I cannot reproduce this with the latest master on a windows machine

```
PS C:\Users\User\Desktop> mkdir -p testano


    Directory: C:\Users\User\Desktop


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/21/2020  11:11 PM                testano


PS C:\Users\User\Desktop> cd .\testano\
PS C:\Users\User\Desktop\testano> C:\Users\User\Desktop\odo.exe create nodejs --starter
Validation
 V  Checking devfile existence [0ns]
 V  Creating a devfile component from registry: DefaultDevfileRegistry [3ms]
 V  Validating devfile component [1ms]

Starter Project
 V  Downloading starter project nodejs-starter from https://github.com/odo-devfiles/nodejs-ex.git [2s]

Please use `odo push` command to create the component with source deployed
PS C:\Users\User\Desktop\testano> ls


    Directory: C:\Users\User\Desktop\testano


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/21/2020  11:12 PM                .odo
d-----       10/21/2020  11:12 PM                test
-a----       10/21/2020  11:12 PM           1644 .gitignore
-a----       10/21/2020  11:12 PM           1374 devfile.yaml
-a----       10/21/2020  11:12 PM          14197 LICENSE
-a----       10/21/2020  11:12 PM          18290 package-lock.json
-a----       10/21/2020  11:12 PM            395 package.json
-a----       10/21/2020  11:12 PM           1189 README.md
-a----       10/21/2020  11:12 PM           1903 server.js
```
Tried on both powershell and cmd. @prietyc123 Please share the `devfile.yaml` data created during the test.

**Comment by prietyc123** [comment]
> I have tried on both powershell and cmd. @prietyc123 Please share the devfile.yaml data created during the test.

@anandrkskd Could you please look into this and confirm once as you are currently working on windows VM.

**Comment by anandrkskd** [comment]
I was also not able to reproduce with latest master,
```
odo create nodejs --starter
Validation
 V  Checking devfile existence [0ns]
 V  Checking devfile compatibility [1ms]
 V  Creating a devfile component from registry: DefaultDevfileRegistry [15ms]
 V  Validating devfile component [996700ns]

Starter Project
 V  Downloading starter project nodejs-starter from https://github.com/odo-devfiles/nodejs-ex.git [425ms]

Please use `odo push` command to create the component with source deployed
PS C:\Users\Admin\ctests> ls


    Directory: C:\Users\Admin\ctests


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/22/2020   7:41 AM                .odo
d-----       10/22/2020   7:41 AM                test
-a----       10/22/2020   7:41 AM           1644 .gitignore
-a----       10/22/2020   7:41 AM           1374 devfile.yaml
-a----       10/22/2020   7:41 AM          14197 LICENSE
-a----       10/22/2020   7:41 AM          18290 package-lock.json
-a----       10/22/2020   7:41 AM            395 package.json
-a----       10/22/2020   7:41 AM           1189 README.md
-a----       10/22/2020   7:41 AM           1903 server.js
```
 and here is the devfile.yaml content for any reference
``` 
schemaVersion: 2.0.0
metadata:
  name: nodejs
  version: 1.0.0
  alpha.build-dockerfile: "https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/build/Dockerfile"
  alpha.deployment-manifest: "https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/deploy/deployment-manifest.yaml"
starterProjects:
  - name: nodejs-starter
    git:
      remotes:
        origin: "https://github.com/odo-devfiles/nodejs-ex.git"
components:
  - name: runtime
    container:
      image: registry.access.redhat.com/ubi8/nodejs-12:1-45
      memoryLimit: 1024Mi
      mountSources: true
      sourceMapping: /project
      endpoints:
        - name: http-3000
          targetPort: 3000
commands:
  - id: install
    exec:
      component: runtime
      commandLine: npm install
      workingDir: /project
      group:
        kind: build
        isDefault: true
  - id: run
    exec:
      component: runtime
      commandLine: npm start
      workingDir: /project
      group:
        kind: run
        isDefault: true
  - id: debug
    exec:
      component: runtime
      commandLine: npm run debug
      workingDir: /project
      group:
        kind: debug
        isDefault: true
  - id: test
    exec:
      component: runtime
      commandLine: npm test
      workingDir: /project
      group:
        kind: test
        isDefault: true
```
