### ISSUE TITLE
odo link to link devfile components with each other

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#3423]
/kind user-story

## User Story
As a user I want to link a devfile component with another devfile component so that I can develop and deploy and a multi-component microservices application on k8s/OCP.

## Acceptance Criteria 
- [ ] `odo push` should create a Secret on the cluster for devfile components
- [ ] `odo link <component-name>`, when executed from a devfile component directory, should link the component with another
- [ ] It should prevent self-linking of component

## Links 
- Related issue: #2920, #1052 (for avoiding self-linking)

/area devfilev2
/area link

**Comment by dharmit** [comment]
Adding needs info to understand how much we need this in this sprint and also to research if we can use Service Binding Operator to link components. I remember reading in their README that we can but I need to read/understand beyond that.

/triage need-information

**Comment by girishramnani** [comment]
also consider the idea of linking a devfile component with an s2i component?

**Comment by dharmit** [comment]
> also consider the idea of linking a devfile component with an s2i component?

If an end-user comes with this request, we can consider adding the support. But since we plan to move away from s2i components, adding this feature doesn't help add much value presently.

**Comment by dharmit** [comment]
When we link one s2i component to another, we inject the data from the secret created at the time of pushing the component. For example, when we link component A with component B (`odo link compB`), component B's secret is injected into component A.

As far as Devfile components are concerned, I don't see us creating a secret for a component like we do for s2i components. Is this a conscious decision in any way? @kadel @girishramnani 

So for the scope of this issue, we will have to:
1. Modify `odo push` to create secrets for the component.
1. Use this secret to link the Deployments using the `Patch` methodology that we used for s2i components.
1. When a component's port configuration is changed, underlying secrets should be altered accordingly.
1. [TBD] - if user changes the port configuration of linked component, should odo be smart enough to modify the link(s) made to this component?
1. Tests
1. Documentation

**Comment by girishramnani** [comment]
ideally shouldn’t we create secrets @dharmit

**Comment by dharmit** [comment]
I tried to link two components without creating a secret for any of them. But that didn't work. I've opened an issue on the SBO repo to understand if doing this is possible using SBO. https://github.com/redhat-developer/service-binding-operator/issues/722

**Comment by dharmit** [comment]
While waiting to get more clarity on how/whether to use SBO to do this, I'm going to start working on the first acceptance criteria of this issue -  `odo push` should create a Secret on the cluster for devfile components. It's something that doesn't depend on whether we decide to use SBO or not.

**Comment by kadel** [comment]
With correct annotations on odo created `Deployments` we should be able to create a ServiceBinding between two odo components https://github.com/redhat-developer/service-binding-operator/blob/master/docs/User_Guide.md#binding-metadata-in-annotations

**Comment by kadel** [comment]
> * [ ]  `odo push` should create a Secret on the cluster for devfile components
> *

Why it should create a Secret? Secret presence is not required for binding. The secret will be created by SBO.

**Comment by kadel** [comment]
each Service generated for odo devfile component should have annotations like this:
```yaml
  annotations:
    service.binding/backend_ip: path={.spec.clusterIP}
    service.binding/backend_port: path={.spec.ports},elementType=sliceOfMaps,sourceKey=name,sourceValue=port
```

`backend` in this example is name of the odo component. It should match what is already in `app.kubernetes.io/name` label.


than the `odo link` command should create link between frontend and backend component
```
cd frontend
odo link backend
```

The resulting `ServiceBinding` should look like this
```yaml
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: java-maven
spec:
  application:
    group: apps
    name: frontend
    resource: deployments
    version: v1
  bindAsFiles: false
  detectBindingResources: true
  services:
    - group: ""
      kind: Service
      name: backend
      version: v1
```

This will expose env variables in frontend compoentn

```
  SERVICE_BACKEND_IP: 10.217.4.62
  SERVICE_BACKEND_PORT_PORT-8080: 8080
```

Note:
`PORT` is twice there because in the example service port has name `port-8080`.
```
  ports:
  - name: port-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
```

If port name is for example `http` the env variable will be `SERVICE_BACKEND_PORT_HTTP: 8080`
But it looks like odo currently autogenerates port names using `PORT_<number>` pattern. This is an issue that should be addressed separately https://github.com/openshift/odo/issues/4737
