### ISSUE TITLE
Devfile v2 issue: Should not give error if other than exec command types present in devfile

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#3429]
/kind bug

<!--

Welcome! - We kindly ask you to:

  1. Fill out the issue template below 
  2. Use the Google group if you have a question rather than a bug or feature request.

The group is at: https://groups.google.com/forum/#!forum/odo-users

Thanks for understanding, and for contributing to the project!

-->

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?

```sh
~/openshift/f                                                                                                                                                                                                                                                                                                                                                               
▶ odo create foo --devfile https://raw.githubusercontent.com/devfile/kubernetes-api/master/devfile-support/samples/simple-devfile.yaml
Experimental mode is enabled, use at your own risk

Validation
 ✓  Creating a devfile component from devfile path: https://raw.githubusercontent.com/devfile/kubernetes-api/master/devfile-support/samples/simple-devfile.yaml [29040ns]
 ✓  Validating devfile component [66356ns]                                                                                                                                                                                                                                                                                                                                  
 
Please use `odo push` command to create the component with source deployed

~/openshift/f                                                                                                                                                                                                                                                                                                                                                               
▶ odo push

Validation
 ✗  Validating the devfile [86168ns]
 ✗  Failed to start component with name foo. Error: Failed to create the component: failed to validate devfile build and run commands: command must be of type "exec"%!!(MISSING)(EXTRA string=
)command must be of type "exec"%!!(MISSING)(EXTRA string=
)
```

See below YAML:

```yaml
  - exec:
      id: helloWorld
      env:
        - name: "USER"
          value: "John Doe"
      commandLine: 'echo "Hello ${USER}"'
```

I have a feeling it's from using quotes within the command. Or this here:

```yaml
  - composite:
      id: buildSchemaAndOpenDevfile
      label: Build schema and open devfile
      commands:
        - buildSchema
        - openDevfile
      parallel: false
```

## Actual behavior

Failure when deploying

## Expected behavior

Being able to crrectly deploy with exec command

## Any logs, error output, etc?
