### ISSUE TITLE
odo create --devfile devfile.yaml, overriding the existing devfile to empty

### ISSUE THREAD

**Issue by adisky** [openshift/odo#3452]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:** master

## How did you run odo exactly?
$ odo create --devfile devfile.yaml

## Actual behavior
I want to deploy component with existing devfile, `odo create --devfile devfile.yaml`, This devfile has lots of configuration added
and `odo create --devfile devfile.yaml` overrided it to empty file.
```
[adisky@localhost convert-to-devfile]$ cat devfile.yaml 
schemaVersion: 2.0.0
metadata:
  name: nodejs
  version: 1.0.0
....
[adisky@localhost convert-to-devfile]$ odo create --devfile devfile.yaml
Experimental mode is enabled, use at your own risk

Validation
 ✓  Creating a devfile component from devfile path: /home/adisky/check-s2i/convert-to-devfile/devfile.yaml [28330ns]
 ✓  Validating devfile component [79173ns]

Please use `odo push` command to create the component with source deployed
[adisky@localhost convert-to-devfile]$ cat devfile.yaml 
```

## Expected behavior
`odo create --devfile devfile.yaml` should not override the existing devfile.yaml, user would lost configured data.

**Comment by GeekArthur** [comment]
To make this issue more specific, the issue only happens when existing devfile and user specify devfile shares the same file system path. Existing devfile and user specify devfile use different paths work for me.

```
    ~/wang/odo-test  cat devfile.yaml                                                                                                                                                          ✔  12:21:45 
schemaVersion: 2.0.0
metadata:
  name: nodejs
  version: 1.0.0
projects:
  - name: nodejs-starter
    git:
      location: "https://github.com/odo-devfiles/nodejs-ex.git"
components:
  - container:
      name: runtime
      image: registry.access.redhat.com/ubi8/nodejs-12:1-36
      memoryLimit: 1024Mi
      mountSources: true
      endpoints:
        - name: http-3000
          targetPort: 3000
          configuration:
            protocol: tcp
            scheme: http
            type: terminal
commands:
  - exec:
      id: install
      component: runtime
      commandLine: npm install
      workingDir: ${CHE_PROJECTS_ROOT}/nodejs-starter
      group:
        kind: build
        isDefault: true
  - exec:
      id: run
      component: runtime
      commandLine: npm start
      workingDir: ${CHE_PROJECTS_ROOT}/nodejs-starter
      group:
        kind: run
        isDefault: true
  - exec:
      id: debug
      component: runtime
      commandLine: npm run debug
      workingDir: ${CHE_PROJECTS_ROOT}/nodejs-starter
      group:
        kind: debug
        isDefault: true
  - exec:
      id: test
      component: runtime
      commandLine: npm test
      workingDir: ${CHE_PROJECTS_ROOT}/nodejs-starter
      group:
        kind: test
        isDefault: true
    ~/wang/odo-test  odo create --devfile ../devfile.yaml                                                                                                                                      ✔  12:21:49 
Experimental mode is enabled, use at your own risk

 ✗  This directory already contains a devfile, you can't specify devfile via --devfile
```
