### ISSUE TITLE
Devfile v2: Breaking change. endpoints.configuration has been moved / removed

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#3544]
/kind feature

## Which functionality do you think we should add?

`configuration` key under `endpoints` has been removed / moved.

See the current schema: https://devfile.github.io/devfile/_attachments/api-reference.html

For example:

```yaml
components:    
  - container:    
      name: runtime    
      image: maysunfaisal/springbootruntime    
      command: ['tail']    
      endpoints:    
        - name: '8080/tcp'    
          configuration:    
            public: true    
            protocol: http
          targetPort: 8080    
```

`configuration` is no longer valid. 

All keys under `configuration` has been moved one key **up**.

Thus the above example is now:

```yaml
components:    
  - container:    
      name: runtime    
      image: maysunfaisal/springbootruntime    
      command: ['tail']    
      endpoints:    
        - name: '8080/tcp'       
          protocol: http
          targetPort: 8080    
```

## Why is this needed?

Change in the API.
