### ISSUE TITLE
Support Kubernetes build and deploy support in odo

### ISSUE THREAD

**Issue by neeraj-laad** [openshift/odo#3583]
/kind feature

## Which functionality do you think we should add?
The following proposal adds support for building a container image and deploying it: 
https://github.com/openshift/odo/blob/master/docs/proposals/odo-deploy.md

There is a PR open to supporting this capability on OpenShift: https://github.com/openshift/odo/pull/3478

We should add support for any Kubernetes as the target.  At a high level this will involve:

- detect when we are not running on Openshift
- use `buildah` or `kaniko` for building the container image
- accept image registry credentials from the user as an argument and use it to push the built image
- support Ingress while detecting the deployed application URL
 
## Why is this needed?
Provide generic Kubernetes support for `odo deploy`

**Comment by neeraj-laad** [comment]
@sbose78 @wtam2018 @jaideepr97 - Lets keep all discussions on Kubernetes path for odo deploy here.

As @EnriqueL8 has mentioned, you can use some aspects fro mhttps://github.com/EnriqueL8/odo/tree/buildah_deploy. This was the work we had started. 

We started looking at buildah first , but were not sure if we could use it without privileged access, were looking to make a switch to kaniko.

**Comment by groeges** [comment]
Raising this comment as a potential change that might be needed when supporting Ingress on Kube (and/or OCP). 

This was something we found when working on the `odo deploy` when attempting to use a deployment manifest that contained an Ingress, ie
```
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: {{.COMPONENT_NAME}}
spec:
  rules:
    - host: {{.COMPONENT_NAME}}-{{.NAMESPACE}}-{{.ROUTE_SUFFIX}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{.COMPONENT_NAME}}
              servicePort: {{.PORT}}-tcp
```
The `spec.rules.host` seems to need to have a host value defined in order to correctly setup the remote URL.
The {{.COMPONENT_NAME}} and {{.NAMESPACE}} template variables are already available within `odo` but the {{.ROUTE_PREFIX}} is not easily obtainable (specifically from OCP - not sure about Kube). 

This may be OCP specific as I have only tried this on Kube running in my Docker Desktop (on Mac) and that Kube setup didn't need the host and just used `localhost`. Just highlighting this just in case it is needed on a full Kube system.
 
There might be a need to include a `--host` (or some suitable named flag) on the `odo deploy` command in order to provide this info when using an Ingress.
