### ISSUE TITLE
Validate lifecycle event commands to a valid container component

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#3655]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:** master

odo should validate event commands and make sure that it maps to a valid component. For example, odo does not validate this on `postStart`:

```
components:
  - container:
      name: "tools"
      image: quay.io/eclipse/che-nodejs10-ubi:nightly
      mountSources: true
      memoryLimit: 1024Mi
commands:
  - exec:
      id: myPostStart
      commandLine: echo I am a PostStart
      component: tools123
      workingDir: /
events:
  postStart:
    - "myPostStart"
```

/area devfile
/assign
