### ISSUE TITLE
Validate comp cmd's child cmd to a valid container component

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#3656]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:** master

Consider this devfile:
```
components:
  - container:
      name: runtime
      image: quay.io/eclipse/che-nodejs10-ubi:nightly
      memoryLimit: 1024Mi
      endpoints:
        - name: "3000/tcp"
          targetPort: 3000 
      mountSources: true
  - container:
      name: "tools"
      image: quay.io/eclipse/che-nodejs10-ubi:nightly
      mountSources: true
      memoryLimit: 1024Mi
commands:
  - exec:
      id: myPostStart
      commandLine: echo I am a PostStart
      component: tools22
      workingDir: /
  - exec:
      id: secondPostStart
      commandLine: echo I am also a PostStart
      component: runtime
      workingDir: /
  - exec:
      id: devrun
      component: runtime
      commandLine: npm start
      workingDir: ${CHE_PROJECTS_ROOT}/nodejs-starter
      group:
        kind: run
        isDefault: true
  - composite:
         id: mycompevent
         label: a comp cmd
         commands:
           - myPostStart
           - secondPostStart
         parallel: true
         group:
          kind: build
          isDefault: true
```

the composite command `mycompevent`'s  `myPostStart` maps to an invalid container component `tools22` with o/p:
```
Executing devfile commands for component madridnode
 •  Executing mypoststart command "echo I am a PostStart"  ...
 •  Executing secondpoststart command "echo I am also a PostStart"  ...
 ✗  
Unable to exec command [/bin/sh -c cd / && echo I am a PostStart]: 

 ✗  Executing mypoststart command "echo I am a PostStart" [518ms]
 ✗  Failed to start component with name madridnode. Error: Failed to create the component: parallel command execution failed: unable to execute the build command: error while streaming command: container tools22 is not valid for pod madridnode-84bc5ff6f4-gr2sd
```

This should be validated. Also remember to check if this holds true for event validation with composite command(subject to https://github.com/openshift/odo/pull/3631 being merged before this is worked on)

/area devfile
