### ISSUE TITLE
devfile with additional configuration for endpoints fails validation

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#3701]
/kind bug

## What versions of software are you using?

**Operating System:**
MacOS

**Output of `odo version`:** master

## How did you run odo exactly?
I have a devfile which looks like this 
```
schemaVersion: 2.0.0
metadata:
  name: nodejs
  version: 1.0.0
projects:
- git:
    location: https://github.com/odo-devfiles/nodejs-ex.git
  name: nodejs-starter
components:
- container:
    endpoints:
    - attributes:
        app.kubernetes.io/managed-by: odo 
      configuration:
        discoverable: true
        protocol: udp
        public: true
      name: port-8080
      targetPort: 8080
    image: registry.access.redhat.com/ubi8/nodejs-12:1-36
    memoryLimit: 768Mi
    mountSources: true
    name: runtime
commands:
- exec:
    commandLine: npm install
    component: runtime
    group:
      isDefault: true
      kind: build
    id: install
    workingDir: ${CHE_PROJECTS_ROOT}/nodejs-starter
- exec:
    commandLine: npm start
    component: runtime
    group:
      isDefault: true
      kind: run
    id: run
    workingDir: ${CHE_PROJECTS_ROOT}/nodejs-starter
- exec:
    commandLine: npm run debug
    component: runtime
    group:
      isDefault: true
      kind: debug
    id: debug
    workingDir: ${CHE_PROJECTS_ROOT}/nodejs-starter
- exec:
    commandLine: npm test
    component: runtime
    group:
      isDefault: true
      kind: test
    id: test
    workingDir: ${CHE_PROJECTS_ROOT}/nodejs-starter
```

now due to having `configuration` for endpoint 
```
configuration:
        discoverable: true
        protocol: udp
        public: true
```

Everything fails 

```
(base) girish@MacBook-Pro buhaha % odo push
 ✗  invalid devfile schema. errors :
- components.0.container.endpoints.0: Additional property configuration is not allowed

```
## Actual behavior
Validation fails
```
(base) girish@MacBook-Pro buhaha % odo push
 ✗  invalid devfile schema. errors :
- components.0.container.endpoints.0: Additional property configuration is not allowed

```

## Expected behavior
Should pass
