### ISSUE TITLE
Devfile mode: the run command process isn't killed, before starting the debug command process, if 'restart' attribute is set as false

### ISSUE THREAD

**Issue by dev-gaur** [openshift/odo#3738]
Pre requisite knowledge :  

the **restart** attribute, as illustrated [here](https://github.com/odo-devfiles/registry/blob/78f685b7476791d9e45a0c9d6bbb8398b93d0216/devfiles/java-quarkus/devfile.yaml#L36)  , enables (when set as true) or disbles (when set as false) the retriggering of a project's build cycle inside the deployed container when `odo push` is used and newly added or edited files are pushed inside the running app container.

#### Case when `restart` attribute to set as true

Using a nodejs project while using the nodejs devfile from the default registry

https://github.com/odo-devfiles/registry/blob/78f685b7476791d9e45a0c9d6bbb8398b93d0216/devfiles/nodejs/devfile.yaml
 
if you see the logs here, it is ensured that the running commands are forcefully killed before the debug command is started. 
![image](https://user-images.githubusercontent.com/7551036/89893055-4f2c5f80-dbf5-11ea-9611-924ba896b80b.png)

#### Case when `restart` attribute to set as false

Using a quarkus project while using this devfile.

```
--- 
  commands: 
    - 
      exec: 
        commandLine: "mvn compile"
        component: tools
        id: init-compile
        workingDir: $PROJECTS_ROOT
    - 
      exec:
        attributes:
          restart: "false"
        commandLine: "mvn quarkus:dev"
        component: tools
        group: 
          isDefault: true
          kind: run
        id: dev-run
        workingDir: $PROJECTS_ROOT
    - 
      exec:
        commandLine: "mvn quarkus:dev -Ddebug=${DEBUG_PORT}"
        component: tools
        group: 
          isDefault: true
          kind: debug
        id: dev-debug
        workingDir: $PROJECTS_ROOT
  components: 
    - 
      container: 
        endpoints: 
          - 
            name: 8080/http
            targetPort: 8080
        image: "quay.io/eclipse/che-quarkus:nightly"
        memoryLimit: 1512Mi
        mountSources: true
        name: tools
        volumeMounts: 
          - 
            name: m2
            path: /home/user/.m2
    - 
      volume: 
        name: m2
        size: 3Gi
  events: 
    postStart: 
      - init-compile
  metadata: 
    name: java-quarkus
    version: "1.0.0"
    website: "https://quarkus.io"
  projects: 
    - 
      git: 
        location: "https://github.com/odo-devfiles/quarkus-ex"
      name: quarkus-ex
  schemaVersion: "2.0.0"  
```

if you see the logs here, the process started by the run command is not killed before starting the debug command process. 
![image (3)](https://user-images.githubusercontent.com/7551036/89895351-49387d80-dbf9-11ea-9954-897f882d00e7.png)

This leads to an error as the port occupied from the run command is not released for the debug command to start properly.

BUT

When I set the restart attribute as true, the ongoing processes are killed before the debug command starts. Check the logs...

![image](https://user-images.githubusercontent.com/7551036/89895592-b4824f80-dbf9-11ea-923d-de0f6c53e2cb.png)
