### ISSUE TITLE
$PROJECT_SOURCE env variable

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3781]
/kind user-story

## User Story
As a Devfile author, I always want to know the exact location of the project source code So that I can execute commands in a current diretory

## Acceptance Criteria 
- [ ] `${PROJECT_SOURCE}` env variable should be available in every container of the component so it can be used in `commandLine` or `workingDir` fields inside Devfiles
- [ ] `${PROJECT_SOURCE}` should point to a directory that contains project source code
   - [ ] if there are multiple projects in  devfile `${PROJECT_SOURCE}` will point to the source code of the first one
   - [ ] if there are no projects in  devfile `${PROJECT_SOURCE}` will be equal to the value of `${PROJECTS_ROOT}`

## Notes
- `${PROJECT_SOURCE}` can be **different for each container** because it depends on  `sourceMapping` value and on `${PROJECTS_ROOT}` value both are set per container.
- Projects source code location inside `${PROJECTS_ROOT}` depends on `clonePath` value (defaults to project name) (https://github.com/openshift/odo/issues/3729)

## Links 
- https://github.com/devfile/api/pull/116
- https://github.com/devfile/api/issues/109#issuecomment-671985647

/kind user-story
/priority high

**Comment by girishramnani** [comment]
so wouldn't this be blocked on https://github.com/openshift/odo/issues/3729 @kadel ?

**Comment by kadel** [comment]
> so wouldn't this be blocked on #3729 @kadel ?

not sure, it could but it also might not :-) It depends how it is handled in odo codebase.

**Comment by girishramnani** [comment]
Prioritise this #3729

**Comment by girishramnani** [comment]
$PROJECT_SOURCE is required for using parent without this env varibale parent devfiles are unusable, but we are not using it anywhere yet

**Comment by girishramnani** [comment]
so it would be ok to implement it after GA

**Comment by maysunfaisal** [comment]
I had a question regarding a use case and wanted to see how we should respond to it. Consider the situation:

### devfile snippet:
```
projects:
  - name: myproj1
    clonePath: myapp1/
    git:
      remotes:
        origin: https://github.com/odo-devfiles/springboot-ex
components:
- name: dummy
  container:
    image: quay.io/eclipse/che-java11-maven:nightly
    memoryLimit: 768Mi
    mountSources: true
    sourceMapping: /test
    command: ['tail']
    args: [ '-f', '/dev/null']
    env:
    - name: PROJECT_SOURCE
      value: /mycustom/path/
```

### explanation:
When a user overwrites `PROJECT_SOURCE` via devfile env. That would mean it would take precedence over a component container's  `sourceMapping` and project's `clonePath` and we would need to overwrite the container's volume mount path to this custom `PROJECT_SOURCE` value now for the project volume.

When this happens, the `sourceMapping`,  `clonePath`  and the existing ENV `PROJECTS_ROOT`(which is decided by `sourceMapping` and the above snippet would be `/test`, `/projects` otherwise), becomes pointless.

1. Is this the correct expected behavior?
2. what should be `PROJECTS_ROOT` in this case? (Note that `PROJECTS_ROOT` is `/mycustom/path/` and `PROJECTS_ROOT` is `/test`)

cc: @kadel @elsony @johnmcollier
