### ISSUE TITLE
odo create should not require cluster access to function

### ISSUE THREAD

**Issue by metacosm** [openshift/odo#3811]
/kind bug

## What versions of software are you using?

**Operating System:** macOS 10.15.6

**Output of `odo version`:** odo v1.2.5 (927826e8d)

## How did you run odo exactly?
`odo create java-quarkus` without being connected to a cluster

## Actual behavior
```
✗  You don't have permission to create or set project 'default' or the project doesn't exist. Please create or set a different project
        odo project create|set <project_name>
```

## Expected behavior
odo should create my component without issue. I should be able to work with odo without a cluster up to the moment I actually want to push to the cluster.

## Any logs, error output, etc?
See above.

**Comment by kadel** [comment]
+1 odo should not require a cluster if it is not needed for a given action

There is no reason why `odo create` should not work without a cluster.

**Comment by johnmcollier** [comment]
Same for `odo catalog list components` https://github.com/openshift/odo/issues/3779

**Comment by prietyc123** [comment]
v2.0.0 has been released, so I am removing the `required-for-v2`

/remove-required-for-v2

**Comment by maxandersen** [comment]
Still an issue. Could.someone add frozen ?

**Comment by kadel** [comment]
Not sure what happened, but this is till a problem that needs to be fixed.

**Comment by kadel** [comment]
Currently `odo create` saves project/namespace name into `env.yaml`. We need to defer this to a later stage (`odo push`).


Acceptance criteria:
-  [ ] `odo create` is not doing anything with the cluster it should not even read anything from `KUBECONFIG`. It needs to work even without Kubernetes client configuration. 
-[ ] If the user runs just `odo create` **without**  specifying component name or flags like `--project`, `--app` `.odo/env/env.yaml` should not be created.
- [ ] If the user runs `odo create java-maven myjava` **without**  any flags. only the `Name` will be recorded in `env.yaml`
  ```yaml
  # env.yaml
  ComponentSettings:
    Name: myjava
  ```
- [ ] If the user runs `odo create` only **with**  `--project`. Only the `Project` will be recorded in `env.yaml`. There should be no check to verify if project/namespace exists or not.
  ```yaml
  # env.yaml
  ComponentSettings:
    Project: myproject
  ```
- [ ] If the user runs `odo create` only **with**  `--app`. Only the `AppName` will be recorded in `env.yaml`
  ```yaml
  # env.yaml
  ComponentSettings:
    AppName: myapp
  ```
- [ ] Any combination of above if possible. `odo create java-maven myjava --project myproject --app myapp` will populate `env.yaml` with correct values.
  ```yaml
  # env.yaml
  ComponentSettings:
    Name: myjava
    Project: myproject
    AppName: myapp
  ```
- [ ] `odo push` can already handle a situation where there is no `env.yaml`. It will also need to handle a situation where `env.yaml` is only partially populated. So for example with
  ```yaml
  # env.yaml
  ComponentSettings:
    AppName: myapp
  ```
  `odo push` command will first have to populate `Name` and `Project` fields with the default values and then perform push action.
