### ISSUE TITLE
breaking change in project definition: update odo to match updated devfile schema

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3862]
Change in devfile schema was recently merged that changes how project location is specified.

This effects both `projects` and `starterProjects` fields

https://github.com/devfile/api/pull/120

old format that is no longer valid
```yaml
projects:
  - name: "devworkspace-spec"
    git:
        location: "https://github.com/devfile/api"
```

New format:
```yaml
projects:
  - name: project   
    git:
      remotes:
        origin: "https://github.com/amisevsk/web-nodejs-sample.git"
```

/priority high
