### ISSUE TITLE
odo allows devfile commands with duplicate ids

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#3886]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?
odo push

## Actual behavior
odo push proceeds

## Expected behavior
odo push should error out on command validation

## Any logs, error output, etc?

this is my devfile.yaml example:
```
components:
  - container:
      name: runtime
      image: registry.access.redhat.com/ubi8/nodejs-12:1-45
      memoryLimit: 1024Mi
      mountSources: true
      sourceMapping: /project
      endpoints:
        - name: http-3000
          targetPort: 3000
  - container:
      name: runtime2
      image: registry.access.redhat.com/ubi8/nodejs-12:1-45
      memoryLimit: 1024Mi
      mountSources: true
      sourceMapping: /project
      command: ['tail']
      args: [ '-f', '/dev/null']
commands:
  - exec:
      id: install
      component: runtime
      commandLine: npm install
      workingDir: /project
      group:
        kind: build
        isDefault: false
  - exec:
      id: install
      component: runtime2
      commandLine: npm install
      workingDir: /project
      group:
        kind: build
        isDefault: false
  - exec:
      id: run
      component: runtime
      commandLine: npm start
      workingDir: /project
      group:
        kind: run
        isDefault: false
  - exec:
      id: run2
      component: runtime
      commandLine: npm start
      workingDir: /project
      group:
        kind: run
        isDefault: false
```

validation does not catch this:

1. duplicate commands `install` reference different components
2. duplicate commands `install` belong to `build` and none are default 

/area devfile
