### ISSUE TITLE
`odo url create` shouldn't require a port if only one port exists in the devfile

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#3923]
/kind bug
/area devfile

## What versions of software are you using?

**Operating System:**
macOS

**Output of `odo version`:**
master

## How did you run odo exactly?
`odo url create --host <ingress-domain>`

## Actual behavior
`odo url create --host <ingress-domain>` without the `--port` flag fails:
```
Johns-MacBook-Pro-3:dev2 johncollier$ odo create --devfile devfile.yaml 
Experimental mode is enabled, use at your own risk

Validation
 ✓  Creating a devfile component from devfile path: /Users/johncollier/ododev/dev2/devfile.yaml [106576ns]
 ✓  Validating devfile component [206951ns]

Please use `odo push` command to create the component with source deployed
Johns-MacBook-Pro-3:dev2 johncollier$ odo url create --host johncollier.ca
 ✗  port must be provided to create an endpoint entry in devfile
```

## Expected behavior
odo detects that there's only one port in the devfile and saves me from manually having to look up the port in the devfile. I believe this was the behaviour in past odo versions.

## Any logs, error output, etc?
Sample devfile:
```
schemaVersion: 2.0.0
metadata:
  name: nodejs
  version: 1.0.0
  alpha.build-dockerfile: "https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/build/Dockerfile"
  alpha.deployment-manifest: "https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/deploy/deployment-manifest.yaml"
starterProjects:
  - name: nodejs-starter
    git:
      remotes:
        origin: "https://github.com/odo-devfiles/nodejs-ex.git"
components:
  - container:
      name: runtime
      image: registry.access.redhat.com/ubi8/nodejs-12:1-45
      memoryLimit: 1024Mi
      mountSources: true
      sourceMapping: /project
      endpoints:
        - name: http-3000
          targetPort: 3000
commands:
  - exec:
      id: install
      component: runtime
      commandLine: npm install
      workingDir: /project
      group:
        kind: build
        isDefault: true
  - exec:
      id: run
      component: runtime
      commandLine: npm start
      workingDir: /project
      group:
        kind: run
        isDefault: true
  - exec:
      id: debug
      component: runtime
      commandLine: npm run debug
      workingDir: /project
      group:
        kind: debug
        isDefault: true
  - exec:
      id: test
      component: runtime
      commandLine: npm test
      workingDir: /project
      group:
        kind: test
        isDefault: true
```

**Comment by maysunfaisal** [comment]
Yeah I found this weird too. But if you dont want to use an ingress, you can just do odo push, and you will have a route that you can use from the default single port in the devfile.

**Comment by johnmcollier** [comment]
@maysunfaisal I was on generic Kube, so had to use an ingress 😉

**Comment by elsony** [comment]
Even if you are using ingress, the user shouldn't need to specify a port if there is only one exposed port. It sounds like a regression since we used to be able to do that in the past.

**Comment by elsony** [comment]
While I am playing around with the beta1 driver, I find the previous behaviour that don't require a port to be specified is much easier to use. Currently, someone new to the devfile support will need to know where to look for the port number in the devfile.yaml even for starter applications.  Our out of the box experience shouldn't require the user to understand the devfile.yaml on day 1 operation.  I think we should fix this so marking this as high priority.

**Comment by johnmcollier** [comment]
So, this is actually a worse bug than I thought, it seems exposing an app is entirely broken on Kube.

This is because when running `odo url create` for a port that's already in the devfile, causes a second entry for that port to be added, rather than the existing entry being modified.

Before:
```
components:
  - name: runtime
    container:
      image: registry.access.redhat.com/ubi8/nodejs-12:1-45
      memoryLimit: 1024Mi
      mountSources: true
      sourceMapping: /project
      endpoints:
        - name: http-3000
          targetPort: 3000
```

After:
```
components:
- name: runtime
  container:
    endpoints:
    - name: http-3000
      targetPort: 3000
    - exposure: public
      path: /
      name: nodejs-3000
      targetPort: 3000
      protocol: http
    image: registry.access.redhat.com/ubi8/nodejs-12:1-45
    memoryLimit: 1024Mi
    mountSources: true
    sourceMapping: /project
```

This causes two bad side effects:
1) The pod always gets restarted on the subsequent `odo push` because a second, duplicate port entry gets added to the deployment
2) (Worse) Because the port is now exposed twice, the ingress creation gets messed up and you can't access the application at all over the created URL.
