### ISSUE TITLE
Re-enable support for the sparseCheckoutDir field in devfiles

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#3933]
/kind bug
/area devfile
/area regression

## What versions of software are you using?

**Operating System:**
macOS

**Output of `odo version`:**
master

## How did you run odo exactly?
`odo create java-openliberty --starter`

## Actual behavior
When cloning a starter project with the `sparseCheckoutDir` field set, `odo create --starter` now clones the entire source code repo specified in the starter project, rather than checking out the directory specified in `sparseCheckoutDir`.

As the java-openliberty devfile currently uses `sparseCheckoutDir` for its starterProject, we're currently unable to use `odo create java-openliberty --starter` and successfully deploy a component from it.

## Expected behavior
`odo create --starter` respects the `sparseCheckoutDir` field in devfiles

## Any logs, error output, etc?
Sample devfile:
```
schemaVersion: 2.0.0
metadata:
  name: nodejs
  version: 1.0.0
starterProjects:
  - name: nodejs-starter
    git:
      remotes:
        origin: "https://github.com/odo-devfiles/nodejs-ex.git"
      sparseCheckoutDir: /test
components:
  - name: runtime
    container:
      image: registry.access.redhat.com/ubi8/nodejs-12:1-45
      memoryLimit: 1024Mi
      mountSources: true
      sourceMapping: /project
      endpoints:
        - name: http-3000
          targetPort: 3000
commands:
  - id: install
    exec:
      component: runtime
      commandLine: npm install
      workingDir: /project
      group:
        kind: build
        isDefault: true
  - id: run
    exec:
      component: runtime
      commandLine: npm start
      workingDir: /project
      group:
        kind: run
        isDefault: true
```

**Comment by adisky** [comment]
it has been discussed here https://github.com/openshift/odo/pull/3867#discussion_r483576554

**Comment by johnmcollier** [comment]
Thanks @adisky. I'll go update the issue title since its disabling was deliberate

In that case I think we need to do two things:
1) Update the `java-openliberty` devfile to not rely on the `sparseCheckoutDir`
2) (in the future) Re-introduce support for the `sparseCheckoutDir`

Have we looked at how Che handles the `sparseCheckoutDir` field? Maybe they have a better approach than what we were doing.

CC @kadel

**Comment by elsony** [comment]
Disabling that will be a problem with the openliberty stack. @scottkurz @ajm01 This means that the liberty starter scenario will not work out of the box as before until this problem is fixed.

**Comment by johnmcollier** [comment]
+1 on updating the devfile to workaround it for now. From Tomas' comment on the PR, it sounds like we weren't handling `sparseCheckoutDir` in a good way, so until we find a good way to get it working, we should make sure the java-openliberty stack is fixed.

If it may take a while to re-introduce the `sparseCheckoutDir` functionality, we may also want to consider adding a warning message to `odo create --starter` when `sparseCheckoutDir` is present in a devfile

**Comment by scottkurz** [comment]
@johnmcollier @elsony  - How would you suggest enabling the ability to have multiple starters?

It would be easy enough to switch to a new repository with a single starter and nothing else, but we intended to offer:

> odo create java-openliberty --starter
> odo create java-openliberty --starter  OtherStarterProj

Can each individual starter get its own relevant config in the devfile?  

(I tried it quick on something close to the odo2 beta and it always checks out the repo root no matter what the --starter arg).



Can each starter

**Comment by johnmcollier** [comment]
@scottkurz So, devfiles can have multiple starter projects and your syntax (`--starter <name>`) is correct. For example:
```
starterProjects:
  - name: nodejs-starter
    git:
      remotes:
        origin: "https://github.com/odo-devfiles/nodejs-ex.git"
  - name: second-starter
    git:
      remotes:
        origin: "https://github.com/johnmcollier/nodejs-ex.git"
      sparseCheckoutDir: /test
```

If `sparseCheckoutDir` were working in odo right now, `odo create --starter second-starter` would checkout the `test` folder from https://github.com/johnmcollier/nodejs-ex.git and `odo create --starter nodejs-starter` would checkout the entire repo.
