### ISSUE TITLE
odo rewrite should preserve "unknown" properties of 'metadata' (and other optional properties?) per devfile schema 

### ISSUE THREAD

**Issue by scottkurz** [openshift/odo#3968]
/kind bug

Per devfile spec schema: 
https://devfile.github.io/devfile/_attachments/api-reference.html

the 'metadata' properties are optional.   

Currently, in 2.0.0-beta-1, the "unknown" properties will be lost during the rewrite that happens, for example, in `odo url create ...`

## What versions of software are you using?

**Operating System:**  Win 10

**Output of `odo version`:**  2.0.0-beta-1

## How did you run odo exactly?

With a devfile like: https://github.com/OpenLiberty/application-stack/blob/master/dev/devfile.yaml

```
schemaVersion: 2.0.0
metadata:
  name: java-openliberty
  version: 0.1.4-rc2
  description: Java application stack using Open Liberty runtime
  alpha.build-dockerfile: "https://raw.githubusercontent.com/OpenLiberty/application-stack/master/dev/Dockerfile"
  alpha.deployment-manifest: "https://raw.githubusercontent.com/OpenLiberty/application-stack/master/dev/app-deploy.yaml"
```

if I do `odo url create --port 9080`  , the devfile will be updated/rewritten but the "alpha.build-dockerfile" and "alpha.deployment-manifest" metadata properties will be lost.

## Expected behavior

Expect these to be preserved.

I just skimmed the devfile spec and didn't see any other examples of optional properties, but not that familiar still.
