### ISSUE TITLE
devfile volume component size bug

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#4004]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:** master

## How did you run odo exactly?
odo push

## Actual behavior
```
Maysuns-MacBook-Pro:springboot-ex maysun$ odo push
 ✗  invalid devfile schema. errors :
- components.1.volume: Invalid type. Expected: object, given: null
```

## Expected behavior
I should be able to define a vol component without a size since its not mandatory. But how is this possible with the new devfile schema where `name` is on the same level as `volume`? 🤔 

```
components:
  - name: tools
    container:
      image: quay.io/eclipse/che-java11-maven:nightly
      memoryLimit: 768Mi
      mountSources: true
      endpoints:
      - name: '8080-tcp'
        targetPort: 8080
      volumeMounts:
        - name: m2
          path: /home/user/.m2
  - name: m2
    volume:
      # size: 3Gi
```

**Comment by maysunfaisal** [comment]
I can skip the size with an empty string, not sure how I feel about that. But probably thats the only option?
```
components:
  - name: tools
    container:
      image: quay.io/eclipse/che-java11-maven:nightly
      memoryLimit: 768Mi
      mountSources: true
      endpoints:
      - name: '8080-tcp'
        targetPort: 8080
      volumeMounts:
        - name: m2
          path: /home/user/.m2
  - name: m2
    volume:
      size: ""
```

**Comment by johnmcollier** [comment]
You can also skip with empty `{}` e.g.:
```
components:
  - name: tools
    container:
      image: quay.io/eclipse/che-java11-maven:nightly
      memoryLimit: 768Mi
      mountSources: true
      endpoints:
      - name: '8080-tcp'
        targetPort: 8080
      volumeMounts:
        - name: m2
          path: /home/user/.m2
  - name: m2
    volume: {}
```
