### ISSUE TITLE
component volumeMount path validation error

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#4005]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:** master

## How did you run odo exactly?
odo push

## Actual behavior
```
Maysuns-MacBook-Pro:springboot-ex maysun$ odo push

Validation
 ✓  Validating the devfile [53446ns]

Creating Kubernetes resources for component myjava
 ✗  Failed to start component with name myjava. Error: Failed to create the component: unable to create or update component: unable to create Deployment myjava: Deployment.apps "myjava" is invalid: spec.template.spec.containers[0].volumeMounts[2].mountPath: Required value
```

## Expected behavior
should default as per https://github.com/openshift/odo/blob/master/docs/file-reference/index.md#volumemountsobject?

## Any logs, error output, etc?

This was my devfile:
```
components:
  - name: tools
    container:
      image: quay.io/eclipse/che-java11-maven:nightly
      memoryLimit: 768Mi
      mountSources: true
      endpoints:
      - name: '8080-tcp'
        targetPort: 8080
      volumeMounts:
        - name: m2
          # path: /home/user/.m2
  - name: m2
    volume:
      size: 2Gi
```

I am not sure if we ever defaulted to `name`. So idk if this is a regression
