### ISSUE TITLE
Overriding parent devfile's commands no longer works

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#4038]
/kind bug
/area devfile

## What versions of software are you using?

**Operating System:**
macOS

**Output of `odo version`:**
master

## How did you run odo exactly?
`odo create --devfile devfile.yaml` where devfile.yaml was a child devfile that overrode a command in the parent devfile

## Actual behavior
```
Johns-MacBook-Pro-3:nodejs johncollier$ odo create --devfile devfile.yaml 
Validation
 ✓  Creating a devfile component from devfile path: /Users/johncollier/ododev/overridecomop/nodejs/devfile.yaml [78443ns]
 ✓  Validating devfile component [89276ns]
 ✗  command install already exists in the devfile
```

## Expected behavior
The child devfile's `install` command properly overrides the `install` command in the parent devfile

## Any logs, error output, etc?
Sample devfile:
```
schemaVersion: 2.0.0
metadata:
  name: nodejs
  version: 1.0.0
parent:
  uri: https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/devfile.yaml
commands:
  - id: install
    exec:
      component: runtime
      commandLine: touch blah.js
      workingDir: ${PROJECTS_ROOT}
      group:
        kind: build
        isDefault: false
```

**Comment by johnmcollier** [comment]
Looks like the cause is this section here:

https://github.com/openshift/odo/blob/master/pkg/devfile/parser/data/2.0.0/components.go#L157-159

With https://github.com/openshift/odo/pull/4001, I'm wondering if we even need this check any more?

**Comment by mik-dass** [comment]
For overriding the command, it should be mentioned in the parent's command section. The above devfile tries to append it in the parent commands which should throw an error. The correct devfile is :

```
schemaVersion: 2.0.0
metadata:
  name: nodejs
  version: 1.0.0
parent:
  uri: https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/devfile.yaml
  commands:
    - id: install
      exec:
        component: runtime
        commandLine: touch blah.js
        workingDir: ${PROJECTS_ROOT}
```
