### ISSUE TITLE
Document how to setup Operators on a minikube cluster

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4103]
/kind documentation

## What mistake did you find / what is missing in the documentation?
odo relies on Service Binding Operator to perform linking of components with Operator backed services. But installing Operators on minikube is not straightforward. There must be a documented way to set things up so that when users are working with odo, everything "just works".

## What is the relevance of it?
It's relevant because linking Operator backed services with odo components is relevant.

Related issue: https://github.com/redhat-developer/service-binding-operator/issues/536

/area service-operators
/area kubernetes
/assign

**Comment by dharmit** [comment]
Scope of this issue is to document installation of etcd Operator and Service Binding Operator on minikube.
* etcd Operator because that's what we have in [our docs](https://odo.dev/docs/operator-hub/#linking-an-odo-component-with-an-operator-backed-service) as an example service that is being linked with a component
* Service Binding Operator because that's what `odo link` uses to create a link

**Comment by dharmit** [comment]
Installing etcd Operator across all the namespaces is as easy as running below yaml with `kubectl create`:
```yaml
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: olm
spec:
  targetNamespaces:
  - olm
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: etcd
  namespace: operators
spec:
  channel: clusterwide-alpha
  name: etcd
  source: operatorhubio-catalog
  sourceNamespace: olm
  startingCSV: etcdoperator.v0.9.4-clusterwide
  installPlanApproval: Automatic
```
And execute:
```sh
$ kubectl create -f etcd.yaml
```
