### ISSUE TITLE
storage create should have the option to specify a container

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#4105]
/kind user-story

## User Story
As a user when I create storage via `odo storage create mynewstorage --size 4Gi --path /some/path`; it creates the volume mount with the specified storage for all the containers if the devfile has more than one container. It should have a flag to specify a container name and should mount storage for only that container.

## Acceptance Criteria 
- [x] It should have a flag for container
- [x] It should validate to check if the container mentioned is valid
- [x] It should mount storage for only the container specified

## Links 
- Feature Request: 
- Related issue: 

/kind user-story

**Comment by maysunfaisal** [comment]
Here is my odo command
```
Maysuns-MacBook-Pro:nodejs-ex maysun$ odo storage create test --path /test
 ✓  Added storage test to no

Please use `odo push` command to make the storage accessible to the component
```

and the devfile with more than one container:
```
components:
- name: runtime
  container:
    endpoints:
    - name: 3000/tcp
      targetPort: 3000
    env:
    - name: FOO
      value: bar
    image: quay.io/eclipse/che-nodejs10-ubi:nightly
    memoryLimit: 1024Mi
    mountSources: true
    volumeMounts:
    - name: firstvol
      path: /data
    - name: test
      path: /test
- name: runtime2
  container:
    image: quay.io/eclipse/che-nodejs10-ubi:nightly
    memoryLimit: 1024Mi
    volumeMounts:
    - name: firstvol
      path: /data
    - name: secondvol
      path: /data2
    - name: test
      path: /test
- name: firstvol
  volume: {}
- name: secondvol
  volume:
    size: 3Gi
- name: test
  volume:
    size: 1Gi
```

**Comment by mohammedzee1000** [comment]
I am currently walking through `url create` and `storage create` and will get back with my findings shortly

**Comment by mohammedzee1000** [comment]
Ok, from what I have read, this might be a little bit more complicated than anticipated.
It is easy enough to add a flag for the container with cobra, and even ensure it gets assigned to LocalStorage

Like so
```golang
	o.storage = localConfigProvider.LocalStorage{
		Name: o.storageName,
		Size: o.storageSize,
		Path: o.storagePath,
		Container: o.container,
	}
```
But doing so is not enough. The creation of the storage happens on 

https://github.com/openshift/odo/blob/ba7161940c735caffaa9bd49e731dd15b8e9a61f/pkg/odo/cli/storage/create.go#L80

The function is present in vendor here

https://github.com/openshift/odo/blob/ba7161940c735caffaa9bd49e731dd15b8e9a61f/vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/volumes.go#L12

As can be seen in the logic below, we iterate over all components and simply add the volume to all of them regardless of what the LocalStorage.Container holds. 

https://github.com/openshift/odo/blob/ba7161940c735caffaa9bd49e731dd15b8e9a61f/vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/volumes.go#L15-L31

The only case where volumes are not added is if container is nil.

I looked at the master branch of the library and it appears to have been sorted, atleast partially with the check for container name match

https://github.com/devfile/library/blob/85a331e08903df1508e2143c2f789703f397e89d/pkg/devfile/parser/data/v2/volumes.go#L15-L29

But this introduces a new issue where if provided container is empty string then it probably will never be added to any container

@kadel @mik-dass what do you guys think / suggest?

**Comment by mohammedzee1000** [comment]
Ok, from what I have read, this might be a little bit more complicated than anticipated.
It is easy enough to add a flag for the container with cobra, and even ensure it gets assigned to LocalStorage

Like so
```golang
	o.storage = localConfigProvider.LocalStorage{
		Name: o.storageName,
		Size: o.storageSize,
		Path: o.storagePath,
		Container: o.container,
	}
```
But doing so is not enough. The creation of the storage happens on 

https://github.com/openshift/odo/blob/ba7161940c735caffaa9bd49e731dd15b8e9a61f/pkg/odo/cli/storage/create.go#L80

The function is present in vendor here

https://github.com/openshift/odo/blob/ba7161940c735caffaa9bd49e731dd15b8e9a61f/vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/volumes.go#L12

As can be seen in the logic below, we iterate over all components and simply add the volume to all of them regardless of what the LocalStorage.Container holds (line no 23 of extract below). 

https://github.com/openshift/odo/blob/ba7161940c735caffaa9bd49e731dd15b8e9a61f/vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/volumes.go#L15-L31

The only case where volumes are not added is if container is nil.

I looked at the master branch of the library and it appears to have been sorted, atleast partially with the check for container name match

https://github.com/devfile/library/blob/85a331e08903df1508e2143c2f789703f397e89d/pkg/devfile/parser/data/v2/volumes.go#L15-L29

But this introduces a new issue where if provided container is empty string then it probably will never be added to any container.
Also https://github.com/openshift/odo/blob/master/vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/volumes.go#L44 seems to be missing in master so global volume ref will not be added to defvile, atleast as far as i can see

@kadel @mik-dass what do you guys think / suggest?

**Comment by mohammedzee1000** [comment]
Also, what happens if i want to add it to multiple ocntainers like mount the same volume to 2/3 containers in devfile?

**Comment by mik-dass** [comment]
> But this introduces a new issue where if provided container is empty string then it probably will never be added to any container.

We can add a check to make sure the container is not nil or empty and throw an error before calling the library's function.

**Comment by kadel** [comment]
> Also https://github.com/openshift/odo/blob/master/vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/volumes.go#L44 seems to be missing in master so global volume ref will not be added to defvile, atleast as far as i can see

Volume in Devfile is just one type of component. You can use `AddComponents`.  `AddVolume` function was removed in favor of `AddComponents` in https://github.com/devfile/library/pull/65.

**Comment by mohammedzee1000** [comment]
> > But this introduces a new issue where if provided container is empty string then it probably will never be added to any container.
> 
> We can add a check to make sure the container is not nil or empty and throw an error before calling the library's function.

What if i want to mount storage on all containers then?

**Comment by mik-dass** [comment]
> What if I want to mount storage on all containers then or m/n containers eg 2/3?

If empty we can mount on all the containers. Not sure about multiple containers but `odo url create` currently doesn't support a list of containers. We can accept a list in case of storage creation. @kadel WDYT?

**Comment by mohammedzee1000** [comment]
> > Also https://github.com/openshift/odo/blob/master/vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/volumes.go#L44 seems to be missing in master so global volume ref will not be added to defvile, atleast as far as i can see
> 
> Volume in Devfile is just one type of component. You can use `AddComponents`. `AddVolume` function was removed in favor of `AddComponents` in [devfile/library#65](https://github.com/devfile/library/pull/65).

I guess that would work. But should this not be done in devfile library than in odo code? as this will mean adding volume mount and global component together will be present only in odo code, basically resulting in divergence in the expected behavior of how devfiles are updated

**Comment by mohammedzee1000** [comment]
> > What if I want to mount storage on all containers then or m/n containers eg 2/3?
> 
> If empty we can mount on all the containers. Not sure about multiple containers but `odo url create` currently doesn't support a list of containers. We can accept a list in case of storage creation. @kadel WDYT?

I guess we can do that. Again change in devfile side will be needed to volume mount add function

**Comment by mohammedzee1000** [comment]
I guess I can start by PRs to devfile library here, although the final step will be upgrading to newer version of library

**Comment by kadel** [comment]
> I guess I can start by PRs to devfile library here, although the final step will be upgrading to newer version of library

library already have everything that you need. To create a new volume you can use ` AddComponents` to mount the volume to existing g container you use `UpdateComponent` and modify or add `volumeMounts` field in container definition.

**Comment by mohammedzee1000** [comment]
In the version that is curr

> > I guess I can start by PRs to devfile library here, although the final step will be upgrading to newer version of library
> 
> library already have everything that you need. To create a new volume you can use ` AddComponents` to mount the volume to existing g container you use `UpdateComponent` and modify or add `volumeMounts` field in container definition.

In the version that is currently vendored into odo? or in master

**Comment by mohammedzee1000** [comment]
ok il call this bit a success:

```
❯ odo storage create commonstorage2 --size 1Gi --path /tmp/common2
 ✓  Added storage commonstorage2 to nodejs-testing-ubbx

Please use `odo push` command to make the storage accessible to the component
❯ cat devfile.yaml
commands:
- exec:
    commandLine: npm install
    component: runtime
    group:
      isDefault: true
      kind: build
    workingDir: /project
  id: install
- exec:
    commandLine: npm start
    component: runtime
    group:
      isDefault: true
      kind: run
    workingDir: /project
  id: run
- exec:
    commandLine: npm run debug
    component: runtime
    group:
      isDefault: true
      kind: debug
    workingDir: /project
  id: debug
- exec:
    commandLine: npm test
    component: runtime
    group:
      isDefault: true
      kind: test
    workingDir: /project
  id: test
components:
- container:
    endpoints:
    - name: http-3000
      targetPort: 3000
    image: registry.access.redhat.com/ubi8/nodejs-14:latest
    memoryLimit: 1024Mi
    mountSources: true
    sourceMapping: /project
    volumeMounts:
    - name: commonstorage
      path: /tmp/common
    - name: commonstorage2
      path: /tmp/common2
  name: runtime
- container:
    image: quay.io/eclipse/che-nodejs10-ubi:nightly
    memoryLimit: 1024Mi
    volumeMounts:
    - name: commonstorage
      path: /tmp/common
    - name: commonstorage2
      path: /tmp/common2
  name: runtime2
- name: commonstorage
  volume:
    size: 1Gi
- name: commonstorage2
  volume:
    size: 1Gi
metadata:
  name: nodejs
  version: 2.0.0
schemaVersion: 2.0.0
starterProjects:
- git:
    remotes:
      origin: https://github.com/odo-devfiles/nodejs-ex.git
  name: nodejs-starter
❯ odo storage create runtime2store --size 1Gi --path /tmp/runtime2 --container runtime2
 ✓  Added storage runtime2store to nodejs-testing-ubbx

Please use `odo push` command to make the storage accessible to the component
❯ cat devfile.yaml
commands:
- exec:
    commandLine: npm install
    component: runtime
    group:
      isDefault: true
      kind: build
    workingDir: /project
  id: install
- exec:
    commandLine: npm start
    component: runtime
    group:
      isDefault: true
      kind: run
    workingDir: /project
  id: run
- exec:
    commandLine: npm run debug
    component: runtime
    group:
      isDefault: true
      kind: debug
    workingDir: /project
  id: debug
- exec:
    commandLine: npm test
    component: runtime
    group:
      isDefault: true
      kind: test
    workingDir: /project
  id: test
components:
- container:
    endpoints:
    - name: http-3000
      targetPort: 3000
    image: registry.access.redhat.com/ubi8/nodejs-14:latest
    memoryLimit: 1024Mi
    mountSources: true
    sourceMapping: /project
    volumeMounts:
    - name: commonstorage
      path: /tmp/common
    - name: commonstorage2
      path: /tmp/common2
  name: runtime
- container:
    image: quay.io/eclipse/che-nodejs10-ubi:nightly
    memoryLimit: 1024Mi
    volumeMounts:
    - name: commonstorage
      path: /tmp/common
    - name: commonstorage2
      path: /tmp/common2
    - name: runtime2store
      path: /tmp/runtime2
  name: runtime2
- name: commonstorage
  volume:
    size: 1Gi
- name: commonstorage2
  volume:
    size: 1Gi
- name: runtime2store
  volume:
    size: 1Gi
metadata:
  name: nodejs
  version: 2.0.0
schemaVersion: 2.0.0
starterProjects:
- git:
    remotes:
      origin: https://github.com/odo-devfiles/nodejs-ex.git
  name: nodejs-starter

```
Now to address comments on PR
