### ISSUE TITLE
Enable 4.6 cluster for odo pr test

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4138]
/kind user-story

## User Story
As a user I want to run prow jobs on 4.6 cluster

## Acceptance Criteria 
- [ ] Fixing the blockers for enabling 4.6 cluster on PRs
- [ ] Jobs should successfully run on 4.6 ocp cluster.

Note: There is already WIP PR https://github.com/openshift/release/pull/10346 which has some blockers. We need to fix those blockers from odo side.

## Links 
- Feature Request: NA
- Related issue: NA

/kind user-story

**Comment by dharmit** [comment]
Since 4.6 is the latest and the greatest OCP version out there, I'm all game for running tests on it. But, I would request that we stick to testing on the specific version of OCP (4.6.x) that CRC ships with. Currently, CRC ships with 4.5.14 but our CI is running on 4.5.15, if I'm not wrong.

I'm requesting this because most devs on the odo team are developing against a minikube or a CRC box. And, I think it's safe to assume that our end users would be using that as well.

**Comment by prietyc123** [comment]
>  CRC ships with 4.5.14 but our CI is running on 4.5.15

Seems @amitkrout  had some progress to fix your concern through this pr https://github.com/openshift/release/pull/11013. @amitkrout Can you please update it.

**Comment by amitkrout** [comment]
> > CRC ships with 4.5.14 but our CI is running on 4.5.15
> 
> Seems @amitkrout had some progress to fix your concern through this pr [openshift/release#11013](https://github.com/openshift/release/pull/11013). @amitkrout Can you please update it.

My bad. I could not follow up my pr since it hit the last platform failure. Anyway i have rebased my pr, as @prietyc123 is on PTO entire this week, so @anandrkskd Please keep eyes on this pr and ping me over slack if it fails again.

**Comment by prietyc123** [comment]
Some of the issue needs to be resolved in order to complete this.

Issues:
- https://github.com/openshift/odo/issues/4036
- https://github.com/openshift/odo/issues/4031
- https://github.com/openshift/odo/issues/4016 (This issue is blocked on https://github.com/openshift/odo/issues/4016#issuecomment-721718782)

So comparatively we are blocked on enabling 4.6 cluster too.

**Comment by prietyc123** [comment]
I have executed our test locally on 4.6 latest stable version and now observing the latest java images are also unsupported from odo side which was not the case before with the unstable build. However I have run basic s2i functionality of odo with image `ubi8/openjdk-11` and it works fine which means we need to add it as supported and release init image the same way as https://github.com/openshift/odo-init-image/pull/72#issuecomment-712093129 . @mohammedzee1000 I have opened a pr https://github.com/openshift/odo-init-image/pull/74 , could you please merge it forcibly and initiate a release process. Afterwards I will open a PR on odo repo to add it in supported list. 

```yaml
$ oc -n openshift get is java -o yaml
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: java
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
[...]
  - annotations:
      description: Build and run Java applications using Maven.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Java (Latest)
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java
      tags: builder,java,openjdk
      version: latest
    from:
      kind: ImageStreamTag
      name: openjdk-11-ubi8
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 11.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 11 (RHEL 7)
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:11,java
      tags: builder,java,openjdk
      version: "11"
    from:
      kind: DockerImage
      name: registry.redhat.io/openjdk/openjdk-11-rhel7:latest
    generation: 2
    importPolicy: {}
    name: openjdk-11-el7
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 11.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 11 (UBI 8)
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:11,java
      tags: builder,java,openjdk
      version: "11"
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi8/openjdk-11:latest
    generation: 2
    importPolicy: {}
    name: openjdk-11-ubi8
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 (RHEL 7)
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:8,java
      tags: builder,java,openjdk
      version: "8"
    from:
      kind: DockerImage
      name: registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:latest
    generation: 2
    importPolicy: {}
    name: openjdk-8-el7
    referencePolicy:
      type: Local
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 8.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 8 (UBI 8)
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:8,java
      tags: builder,java,openjdk
      version: "8"
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi8/openjdk-8:latest
    generation: 2
    importPolicy: {}
    name: openjdk-8-ubi8
    referencePolicy:
      type: Local
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/openshift/java
  tags:
 [...]
  - items:
    - created: "2020-11-09T05:45:23Z"
      dockerImageReference: registry.redhat.io/ubi8/openjdk-11@sha256:5743bc7c45fce643862773cd1b4e9738cca2ea223c1e4566d71d3788c7ab4b38
      generation: 2
      image: sha256:5743bc7c45fce643862773cd1b4e9738cca2ea223c1e4566d71d3788c7ab4b38
    tag: latest
  - items:
    - created: "2020-11-09T05:45:23Z"
      dockerImageReference: registry.redhat.io/openjdk/openjdk-11-rhel7@sha256:442eda2f44aba32a17aab2d47d36543d0b84732b7553bc5db2e90e1d9ba55d14
      generation: 2
      image: sha256:442eda2f44aba32a17aab2d47d36543d0b84732b7553bc5db2e90e1d9ba55d14
    tag: openjdk-11-el7
  - items:
    - created: "2020-11-09T05:45:23Z"
      dockerImageReference: registry.redhat.io/ubi8/openjdk-11@sha256:5743bc7c45fce643862773cd1b4e9738cca2ea223c1e4566d71d3788c7ab4b38
      generation: 2
      image: sha256:5743bc7c45fce643862773cd1b4e9738cca2ea223c1e4566d71d3788c7ab4b38
    tag: openjdk-11-ubi8
  - items:
    - created: "2020-11-09T05:45:23Z"
      dockerImageReference: registry.redhat.io/redhat-openjdk-18/openjdk18-openshift@sha256:fa5f725ba5d0ed29f680a21d49e87d88ef0bad3db83158496eda33533cca10f8
      generation: 2
      image: sha256:fa5f725ba5d0ed29f680a21d49e87d88ef0bad3db83158496eda33533cca10f8
    tag: openjdk-8-el7
  - items:
    - created: "2020-11-09T05:45:23Z"
      dockerImageReference: registry.redhat.io/ubi8/openjdk-8@sha256:43a0bf425a428380a741b6c168a0de438a267bfcd31e982e23c6965d5dfeb9e6
      generation: 2
      image: sha256:43a0bf425a428380a741b6c168a0de438a267bfcd31e982e23c6965d5dfeb9e6
    tag: openjdk-8-ubi8
```
