### ISSUE TITLE
Support Kubernetes Devfile component

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4159]
/kind feature

service operations should occur on odo push. we need to store the service information in the `Component` as a CR in the devfile.

**Comment by kadel** [comment]
In order for this to work, we first need to add support for `kubernetes` components.

Devfile can specify kubernetes component like this:

```
components:
  - name: my-mongo
    kubernetes:
      inlined: >
        apiVersion: v1
        kind: Pod
        metadata:
          name: nginx
          labels:
            name: nginx
        spec:
          containers:
          - name: nginx
            image: nginx
            ports:
            - containerPort: 80
```
or
```
components:
  - name: my-mongo
    kubernetes:
      inlined: >
        apiVersion: mongodb.com/v1
        kind: MongoDB
        metadata:
          name: my-replica-set
          namespace: tkral-test
        spec:
          credentials: my-credentials
          members: 3
          opsManager:
            configMapRef:
              name: my-project
          type: ReplicaSet
          version: 4.4.0-ent
          persistent: true
        status:
          phase: Running
          type: ReplicaSet
```

The idea is that the content of a `kubernetes` component can be any Kubernetes resource (core one, or custom resource).

`odo push` needs to recognize `kubernetes` components and apply them to the cluster.
