### ISSUE TITLE
odo devfile test execution in disconnected cluster

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4200]
/kind documentation

## What mistake did you find / what is missing in the documentation?

Currently there is no documentation on how to test odo devfile within disconnected cluster. It has been elaborated in https://github.com/openshift/odo/issues/3138#issuecomment-722393426

**Comment by prietyc123** [comment]
Steps followed for odo devfile execution on disconnected cluster

- Create a disconnected cluster
-  Login to the disconnected env
-  Allow required URLs in the proxy (raw.githubusercontent.com, registry.access.redhat.com and registry.npmjs.org) for the devfile
-  add the proxy in the devfile as an env var to install npm
devfile example:

```yaml
schemaVersion: 2.0.0
metadata:
  name: nodejs
starterProjects:
  - name: nodejs-starter
    git:
      remotes:
        origin: "https://github.com/odo-devfiles/nodejs-ex.git"
components:
  - name: runtime
    container:
      image: registry.access.redhat.com/ubi8/nodejs-12:1-36
      memoryLimit: 1024Mi
      endpoints:
        - name: "3000/tcp"
          targetPort: 3000
      env:
        - name: HTTP_PROXY
          value: http://<proxy-host>:3128
        - name: HTTPS_PROXY
          value: http://<proxy-host>:3128
      mountSources: true
commands:
  - id: devbuild
    exec:
      component: runtime
      commandLine: npm install
      workingDir: ${PROJECTS_ROOT}
      group:
        kind: build
        isDefault: true
  - id: build
    exec:
      component: runtime
      commandLine: npm install
      workingDir: ${PROJECTS_ROOT}
      group:
        kind: build
  - id: devrun
    exec:
      component: runtime
      commandLine: npm start
      workingDir: ${PROJECTS_ROOT}
      group:
        kind: run
        isDefault: true
  - id: run
    exec:
      component: runtime
      commandLine: npm start
      workingDir: ${PROJECTS_ROOT}
      group:
        kind: run
```
-  Run devfile test 

Some of the test execution steps are mentioned in [comment](https://github.com/openshift/odo/issues/3138#issuecomment-722393426)

ping @boczkowska
