### ISSUE TITLE
Unable to list services

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4203]
I'm logged in to the cluster  I can list `CSV`s
```
▶ oc get csv
NAME                                  DISPLAY                    VERSION             REPLACES   PHASE
etcdoperator.v0.9.4-clusterwide       etcd                       0.9.4-clusterwide              Succeeded
mongodb-enterprise.v1.8.0             MongoDB                    1.8.0                          Succeeded
service-binding-operator.v0.1.1-364   Service Binding Operator   0.1.1-364                      Succeeded
```
But odo catalog list services is complaining

```
▶ odo catalog list services
 ✗  unable to list services because neither Service Catalog nor Operator Hub is enabled in your cluster: unable to get cluster serviceClassExternalName: unable to get cluster service classes: unable to list cluster service classes: clusterserviceclasses.servicecatalog.k8s.io is forbidden: User "tkral" cannot list resource "clusterserviceclasses" in API group "servicecatalog.k8s.io" at the cluster scope
```

/area service
/area service-operators
/kind bug

**Comment by gorkem** [comment]
This is a show stopper

**Comment by kadel** [comment]
interestingly enough I can instantiate services
```
▶ odo service create mongodb-enterprise.v1.8.0/MongoDB --dry-run
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-replica-set
spec:
  credentials: my-credentials
  members: 3
  opsManager:
    configMapRef:
      name: my-project
  persistent: true
  type: ReplicaSet
  version: 4.4.0-ent
status:
  phase: Running
  type: ReplicaSet


▶ odo service create mongodb-enterprise.v1.8.0/MongoDB
Deploying service of type: MongoDB
 ✓  Deploying service [156ms]
 ✓  Service '' was created

Progress of the provisioning will not be reported and might take a long time
You can see the current status by executing 'odo service list'
Optionally, link mongodb-enterprise.v1.8.0 to your component by running: 'odo link <component-name>'
````


It looks like something is just broken in catalog listing
