### ISSUE TITLE
env variables in exec commands are not properly exported

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4232]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?

I have a devfile that defines a command spawning new shell, for example like this:

```yaml
  - id: build 
    exec:
      component: tools
      commandLine: "sh -c 'echo foo is $foo'"
      group:
        kind: build
        isDefault: true
      env:
        - name: foo
          value: bar
```

## Actual behavior

```
▶ odo push --show-log

Validation
 ✓  Validating the devfile [56469ns]

Creating Kubernetes resources for component java-maven
 ✓  Waiting for component to start [26s]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component java-maven
 ✓  Checking file changes for pushing [1ms]
 ✓  Syncing files to the component [2s]

Executing devfile commands for component java-maven
 •  Executing build command "sh -c 'echo foo is $foo'"  ...
foo is
```

## Expected behavior

```▶ odo push --show-log

Validation
 ✓  Validating the devfile [56469ns]

Creating Kubernetes resources for component java-maven
 ✓  Waiting for component to start [26s]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component java-maven
 ✓  Checking file changes for pushing [1ms]
 ✓  Syncing files to the component [2s]

Executing devfile commands for component java-maven
 •  Executing build command "sh -c 'echo foo is $foo'"  ...
foo is bar
```
notice the last line, it should print the correct value of $foo value

## more info
When command defines the env variable than odo executes it as `<env.name>=<env.value> && <commandLine>`.
But the correct behavior should be `export <env.name>=<env.value> && <commandLine>`. Export is important as it will make sure that the variable is available in all subshells not just in the current shell.

This is not just for `build` command, but for `run` and any other commands that have this behavior.

/priority high
/kind bug
