### ISSUE TITLE
Docker rate limit issue being hit on clusters without docker pull secret in PSI

### ISSUE THREAD

**Issue by mohammedzee1000** [openshift/odo#4278]
Error:

```
Running oc with args [oc --request-timeout 5m import-image nodejs:latest --namespace=dxtqvnnbwd --from=docker.io/centos/nodejs-10-centos7:latest --confirm]

[oc] error: tag latest failed: Internal error occurred: docker.io/centos/nodejs-10-centos7:latest: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by mohammedzee1000** [comment]
Possible fixes:
 - Use registry.centos.org for acquiring the CentOS images, instead of docker.io (recommended)
 - Configure an authenticated docker pull secret on internal clusters (this includes a robot account)

nodejs-10-centos7 is already available in r.c.o https://github.com/CentOS/container-index/blob/master/index.d/centos.yaml#L989-L999 and I have a PR to add nodejs-14-centos7 to the index already https://github.com/CentOS/container-index/pull/412.

This registry is more under our control as @bamachrn is maintaining it and me and @dharmit have already worked on it.

**Comment by prietyc123** [comment]
> Use registry.centos.org for acquiring the CentOS images, instead of docker.io 

@mohammedzee1000 AFAIK using r.c.o would limit the access of images, rather If we want to be generalized with docker/external images why not onboard with `app-sre` team. We just need to use mirror mechanism from docker to quay.io and for onboarding the project create `app.yaml` in their services repo with the yamls.

```yaml
quayRepos:
- org:
    ...
  items:
  - name: my-private-repo
    ...
    mirror:
      $ref: /dependencies/image-mirrors/docker.io/me/my-private-repo.yml
```

The `$ref` file content would then be:

```yaml
---
$schema: /dependencies/container-image-mirror-1.yml

url: docker.io/me/my-private-repo

pullCredentials:
  path: app-sre/creds/mirror-images/docker-io_me_my-private-repo
  field: all

tags:
  - "latest"
```
For more details we can ping `@app-sre-ic` .
