### ISSUE TITLE
Add ubi/nodejs-14 image as Supported

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4303]
/kind user-story

## User Story
As a user I want to execute odo on ocp 4.7 with latest nodejs image

## Acceptance Criteria 
- [ ] latest nodejs image on 4.7 should supported in odo
- [ ] Tests should run successfully on 4.7

## Links 
- Feature Request: NA
- Related issue: https://github.com/openshift/odo/issues/4280

/kind user-story

**Comment by prietyc123** [comment]
Latest nodejs image on ocp 4.7 is

$ oc -n openshift get is nodejs -o yaml
```yaml
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nodejs
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
 [...]
  - annotations:
      description: |-
        Build and run Node.js applications on UBI. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-nodejs-container/blob/master/14/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Node.js available on OpenShift, including major version updates.
      iconClass: icon-nodejs
      openshift.io/display-name: Node.js (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/nodejs-ex.git
      supports: nodejs
      tags: builder,nodejs
    from:
      kind: ImageStreamTag
      name: 14-ubi8
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/openshift/nodejs
  tags:
 [...]
  - items:
    - created: "2020-12-10T02:54:47Z"
      dockerImageReference: registry.redhat.io/ubi8/nodejs-14@sha256:a11fcdd5745528634b9fd149b28d3d0bcac174e79d51d12a3241c7da886fde35
      generation: 2
      image: sha256:a11fcdd5745528634b9fd149b28d3d0bcac174e79d51d12a3241c7da886fde35
    tag: latest
```
