### ISSUE TITLE
"odo url create" asks for port when devfile exposes two ports but a container exposes only one port

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4330]
## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:**
```
$ odo version
odo v2.0.3 (96fc76e69)
```

## How did you run odo exactly?
1. Used below devfile.yaml from #4318:
    ```yaml
    schemaVersion: 2.0.0
    metadata:
      name: nodejs
      version: 1.0.0
      attributes:
        alpha.build-context: src
        alpha.build-dockerfile: Dockerfile
    components:
      - name: buildguidance
        container:
          image: buildguidanceimage-placeholder
          memoryLimit: 1024Mi
          endpoints:
            - name: http-3001
              targetPort: 3001
      - name: runtime
        container:
          image: registry.access.redhat.com/ubi8/nodejs-12:1-45
          memoryLimit: 1024Mi
          mountSources: true
          sourceMapping: /project
          endpoints:
            - name: http-3000
              targetPort: 3000
    commands:
      - id: install
        exec:
          component: runtime
          commandLine: npm install
          workingDir: /project/src
          group:
            kind: build
            isDefault: true
      - id: run
        exec:
          component: runtime
          commandLine: npm start
          workingDir: /project/src
          group:
            kind: run
            isDefault: true
    ```
1. Did `odo create nodejs --devfile devfile.yaml`
2. Tried to create URL with `--container` flag.

## Actual behavior
```sh
$ odo url create --host `minikube ip`.nip.io --container buildguidance
 ✗  port for the component nodejs is required as it exposes 2 ports: 3000,3001

$ odo url create --host `minikube ip`.nip.io --container runtime      
 ✗  port for the component nodejs is required as it exposes 2 ports: 3001,3000
```

## Expected behavior
Both `runtime` and `buildguidance` containers in the devfile expose one port each. odo should not ask the user to specify port number in such case and be smart enough to create URL for the port exposed by the specified container.

## Any logs, error output, etc?
Kudos for odo being smart to prevent user from creating URL for invalid container-port combination. Below commands rightly fail:
```sh
$ odo url create --host `minikube ip`.nip.io --container runtime --port 3001
 ✗  cannot set URL nodejs-3001 under container runtime, TargetPort 3001 is being used under container buildguidance

$ odo url create --host `minikube ip`.nip.io --container buildguidance --port 3000
 ✗  url nodejs-3000 already exist in devfile endpoint entry under container runtime
```

/area url
/priority medium
/kind bug
