### ISSUE TITLE
spring-petclinic never working on dev sandbox

### ISSUE THREAD

**Issue by sspeiche** [openshift/odo#4400]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:** 
2.0.4

## How did you run odo exactly?
odo push

## Actual behavior
Everything started but app not working, route failed to resolve not errors in log

## Expected behavior
Importing from Git it compiles and deploys fine.

## Any logs, error output, etc?
No errors from push

Repo: https://github.com/sspeiche/spring-petclinic/tree/devfile (devfile branch is where I have new devfile)
Service, running out of my sspeiche-dev project: https://developers.redhat.com/developer-sandbox

**Comment by kadel** [comment]
After running the following steps I got an error from the application `Caused by: java.net.UnknownHostException: mysql: Name or service not known`
It looks like
```
git clone https://github.com/sspeiche/spring-petclinic
cd spring-petclinic
git checkout devfile
odo push
odo log
```

the devfile.yaml contains the following  env variable
```
    - name: MYSQL_URL
      value: jdbc:mysql://mysql:3306/petclinic
```
I guess the application tries to connect to  MySQL instance at `mysql` hostname. Services are not deployed automatically by odo.  You will have to create MySQL instance using `odo service create` This will require MySQL operator to be installed first. I'm not sure if DevSandbox allows users to install operators.

**Comment by kadel** [comment]
I was able to get it working with mysql-ephemeral OpenShift tamplete deployed from Developer Catalog.
And updating the environment variables in Devfile

```yaml
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: mysql
    - name: MYSQL_URL
      value: jdbc:mysql://mysql:3306/sampledb
    - name: MYSQL_USER
      value: user3UO
    - name: MYSQL_PASS
      value: MBxW4jEMQAwDtNbe
```
