### ISSUE TITLE
Align labels with dev console

### ISSUE THREAD

**Issue by sspeiche** [openshift/odo#4544]
/kind feature

As a developer, I'd like to ensure that applications/component I construct with `odo` or other clients like OpenShift Dev Console so that I can get a consistent view of my application/components.

For example, odo doesn't always set the git repo URL when it could know it. It would be helpful to populate the link/annotation that drive the experience and some capabilities.

See Dev Console label/annotation doc (need to dig up link)

**Comment by sspeiche** [comment]
FYI @serenamarie125

**Comment by kadel** [comment]
Annotations that DevConsole is using should be the same as described in https://github.com/redhat-developer/app-labels

**Comment by mik-dass** [comment]
Currently, a component by odo can have the following annotations and labels
```
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    app: app
    app.kubernetes.io/instance: nodejs-project-kjoq
    app.kubernetes.io/managed-by: odo
    app.kubernetes.io/managed-by-version: v2.2.1
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: app
    component: nodejs-project-kjoq
```
and a component by dev console can have the following annotations and labels
```
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/sclorg/nodejs-ex'
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"nodejs-ex:latest","namespace":"blah"},"fieldPath":"spec.template.spec.containers[?(@.name==\"nodejs-ex\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: nodejs-ex
    app.kubernetes.io/component: nodejs-ex
    app.kubernetes.io/instance: nodejs-ex
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: nodejs-ex-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 14-ubi7
```
