### ISSUE TITLE
Inconsistency between  `odo registry` output and `preference.yaml`

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4626]
https://github.com/openshift/odo/pull/4525/ introduced support for the new OCI registry and a migration path to it.

Problem is that it also creates inconsistency between what `odo registry list` shows and what is in `preference.yaml`.

Ideally, odo should change the preference file as well and store the new registry URL there. 

```
▶ odo registry list
NAME                       URL                                                       SECURE
demo                       https://raw.githubusercontent.com/kadel/registry/demo     No
DefaultDevfileRegistry     https://registry.devfile.io                               No
```

```
▶ cat ~/.odo/preference.yaml
kind: Preference
apiversion: odo.dev/v1alpha1
OdoSettings:
  BuildTimeout: 5
  RegistryList:
  - Name: DefaultDevfileRegistry
    URL: https://github.com/odo-devfiles/registry
    secure: false
  - Name: demo
    URL: https://raw.githubusercontent.com/kadel/registry/demo
    secure: false
  ConsentTelemetry: false
````
