### ISSUE TITLE
Support using built-in resource types for inlined Kubernetes-typed components

### ISSUE THREAD

**Issue by scottkurz** [openshift/odo#4685]
/kind bug

## What versions of software are you using?

**Operating System:** Win10, Linux

**Output of `odo version`:** odo v2.1.0 (8479050f6)

## How did you run odo exactly?

Well, I'm not saying I had a compelling business or technical case for doing this, but just to understand the technology, I tried adding some buit-in type defs as inlined kubernetes-typed components, like this:

```yaml
components:
  - name: myk8deploy
    kubernetes:
      inlined: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: nginx
          labels:
            name: nginx
        spec:
          containers:
          - name: nginx
            image: nginx
            ports:
            - containerPort: 80
```

(Note there's no reference to this component from any of the `commands`.)

  
## Actual behavior

In the VSCode debug console I see: 

>  Failed to start component with name "in1". Error: Failed to create the component: failed to create service(s) associated with the component: could not find specified service/custom resource: Pod; please check the "kind" field in the yaml (it's case-sensitive)

and nothing matching the nginx pod in the namespace via `kubectl get all`.

In the debugger I see we step through:

```go
func GetCSV(client *kclient.Client, crd map[string]interface{}) (string, olm.ClusterServiceVersion, error) {
	cr := crd["kind"].(string)
	csvs, err := client.ListClusterServiceVersions()
```

fail to find a CSV match for the Pod type, and exit.

## Expected behavior

I'd expect this definition to have been passed to "kubectl apply".   odo shouldn't only be creating operator-backed resources.

## Any logs, error output, etc?

See above

## LINK

This could be grouped with this issue: https://github.com/openshift/odo/issues/4159
