### ISSUE TITLE
odo catalog describe service <operator> --example

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#4796]
/kind feature

## Which functionality do you think we should add?
`odo catalog describe service <operator> --example` should print the alm-example present in the CSV for that operator.

## Why is this needed?
Sometimes the `odo catalog describe service <operator` is too overwhelming for the user as it could hold all the possible parameters that an operator consumes. A user might just want to see an example. I personally felt the need for this when I implemented https://github.com/openshift/odo/pull/4704

**Comment by girishramnani** [comment]
This is really straight-forward to implement as we would just print what we have in `odo service create <operator> --dry-run`.
Now assuming dry-run has a json output, we use that or we just convert the `odo service create <operator> --dry-run` output to a json ( as its yaml in human readable output )
Sample expected output

```
odo catalog describe service  postgresql-operator.v0.1.1/Database --example
apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
  name: database
spec:
  databaseCpu: 30m
  databaseCpuLimit: 60m
  databaseMemoryLimit: 512Mi
  databaseMemoryRequest: 128Mi
  databaseName: example
  databaseNameKeyEnvVar: POSTGRESQL_DATABASE
  databasePassword: postgres
  databasePasswordKeyEnvVar: POSTGRESQL_PASSWORD
  databaseStorageRequest: 1Gi
  databaseUser: postgres
  databaseUserKeyEnvVar: POSTGRESQL_USER
  image: centos/postgresql-96-centos7
  size: 1
```
