### ISSUE TITLE
odo service create -p --dry-run should show "parametrized" crd

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4813]
/kind bug

## What versions of software are you using?

**Output of `odo version`:**
```
▶ odo version
odo v2.2.2 (0e9e9717d)

Server: https://api.crc.testing:6443
Kubernetes: v1.20.0+75370d3
```

## How did you run odo exactly?
`odo service create  postgresql-operator.v0.1.1/Database -p databaseName=mydb -p databaseUser=user -p databasePassword=pass  --dry-run`

## Actual behavior
shows alm-example
```
apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
  name: database
spec:
  databaseCpu: 30m
  databaseCpuLimit: 60m
  databaseMemoryLimit: 512Mi
  databaseMemoryRequest: 128Mi
  databaseName: example
  databaseNameKeyEnvVar: POSTGRESQL_DATABASE
  databasePassword: postgres
  databasePasswordKeyEnvVar: POSTGRESQL_PASSWORD
  databaseStorageRequest: 1Gi
  databaseUser: postgres
  databaseUserKeyEnvVar: POSTGRESQL_USER
  image: centos/postgresql-96-centos7
  size: 1
```

## Expected behavior
the flag is called --dry-run, so it should show what will be created

in the above command with parameters it should who
```
      apiVersion: postgresql.dev4devs.com/v1alpha1
      kind: Database
      metadata:
        name: database
      spec:
        databaseName: mydb
        databasePassword: pass
        databaseUser: user
```

If executed without parameters it should show alm-example

/kind bug
/priority high
