### ISSUE TITLE
Nightly tests against latest Service Binding Operator

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4942]
## User Story
As an odo developer, I want to have nightly tests of main branch of odo against [master branch of Service Binding Operator](https://github.com/redhat-developer/service-binding-operator) so that we can prepare ourselves for any breaking changes that might land in, or notify the Service Binding Operator team about a change on their side that could break odo.

#### QE
- [ ] Set up a job that tests only the integration between main branch of odo and master branch of SBO.
- [ ] Create a file to trigger nightly test with only `operatorhub linking` test in execution.
- [ ] Modify operator setup script to use latest sbo catalog source and then install
- [ ] Make sure that `odo link` and subsequent `odo push` work 100% of the times.
- [ ] Failures should notify the odo team in appropriate way along with failure logs.

#### Dev
- [x] Have integration tests that check for existence of the Service Binding, the Secret created by it, and presence of environment variables with appropriate values in the odo component's Pod.
- [x] Integration tests for everything mentioned above when `bind-as-files` is used.
- [ ] ~Integration tests for everything above when Service Binding Operator is not installed.~

## Links 
- Related Epic (mandatory): N/A

/kind user-story
/area testing
/area linking

**Comment by dharmit** [comment]
This issue is an outcome of the problems faced by odo after the release of v0.9.0 of SBO. 
Relevant issues: #4940 & #4936.

**Comment by kadel** [comment]
How to deploy SBO master build to OCP:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: service-binding-master
  namespace: openshift-marketplace
spec:
  displayName: Service Binding Operator build from master
  image: quay.io/redhat-developer/servicebinding-operator:index
  priority: 500
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m0s

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: service-binding-operator
  namespace: openshift-operators
spec:
  channel: beta
  installPlanApproval: Automatic
  name: service-binding-operator
  source: service-binding-master
  sourceNamespace: openshift-marketplace
```


The first resource adds sbo catalog index to ocp, second one installs the SBO from that catalog.
