### ISSUE TITLE
How to extend the catalog to include by example Spring Boot component 

### ISSUE THREAD

**Issue by cmoulliard** [openshift/odo#500]
It is not possible to create a `spring-boot` component as the list returned by the catalog doesn't include it 

```
/Users/dabou/Code/go-workspace/bin/odo catalog list
The following components can be deployed:
- dotnet
- httpd
- nginx
- nodejs
- perl
- php
- python
- ruby
- wildfly
```

What should we do to include it and extend the catalog ?

**Comment by cmoulliard** [comment]
On minishift = ocp 3.9 the Red Hat OpenJDK1.8 S2I image is not added by default
If I create the following s2i imagestream, them odo can list within the catalog

```
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openjdk18
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations:
        description: >-
          Build and run Java Microservices such as Spring Noot
        iconClass: icon-spring
        openshift.io/display-name: OpenJDK 1.8 (Latest)
        openshift.io/provider-display-name: 'Red Hat, Inc.'
        tags: 'builder,java,spring-boot'
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
```
