### ISSUE TITLE
service creation fails with wrong namespace

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#5019]
/kind bug


## What versions of software are you using?

**Operating System:** Win10Pro

**Output of `odo version`:**

```
odo v2.3.0 (089b8ea26)

Server: https://api.sandbox.x8i5.p1.openshiftapps.com:6443
Kubernetes: v1.20.0+558d959
```

## How did you run odo exactly?
```
odo service create rhoas-operator.0.7.8/KafkaConnection
odo push

```
## Actual behavior

```
Validation                                                                                                                                                                                     
 V  Validating the devfile [0ns]                                                                                                                                                               
                                                                                                                                                                                               
Creating Services for component ncomp                                                                                                                                                          
 X  Failed to start component with name "ncomp". Error: Failed to create the component: failed to create service(s) associated with the component: the namespace of the provided object does not match the namespace sent on the request                                                                                                                                                      
```
                                                                                                                                                                                               

## Expected behavior

Service should be created

## Any logs, error output, etc?

`odo service create rhoas-operator.0.7.8/KafkaConnection --dry-run` gives the following output:

```
apiVersion: rhoas.redhat.com/v1alpha1                       
kind: KafkaConnection                                       
metadata:                                                   
  labels:                                                   
    app.kubernetes.io/component: external-service           
    app.kubernetes.io/managed-by: rhoas                     
  name: example                                             
  namespace: example-namespace                              
spec:                                                       
  accessTokenSecretName: rh-managed-services-api-accesstoken
  credentials:                                              
    serviceAccountSecretName: service-account-secret        
  kafkaId: exampleId                                        
```
