### ISSUE TITLE
`odo link` flow broken on latest SBO 0.10.

### ISSUE THREAD

**Issue by kadel** [openshift/odo#5084]
https://github.com/redhat-developer/service-binding-operator/releases/tag/v0.10.0

Latest SBO introduced changes that required explicitly create `RoleBindings` in order for SBO to  be able to read information from CustomResources.

Ideally this `RoleBinding` should be automaticaly created when Operator that supports ServiceBinding gets installed.
But currently there are no Operator that would support SBO out of the box.

This means that when someone installs Operator that they want to use with SBO with,  they need to create `RoleBinding` manually. This needs to be done with cluster admin privileges.

For example this is `ClusterRole` required for postresql from dev4devs operator.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresql-binding
  labels:
    service.binding/controller: "true"
rules:
  - apiGroups:
      - postgresql.dev4devs.com
    resources:
      - databases
    verbs:
      - get
      - list

---

apiVersion: rbac.authorization.k8s.io/v1        
kind: ClusterRoleBinding
metadata:
  name: postgresql-binding-sbo
subjects:
- kind: ServiceAccount
  name: service-binding-operator
  namespace: openshift-operators
roleRef:
  kind: ClusterRole
  name: postgresql-binding
  apiGroup: rbac.authorization.k8s.io

```

We need to document this in odo docs.  As without this users won't be able to use `odo link` with SBO.

/priority critical
