### ISSUE TITLE
odo overwrites devfile with parent reference with flattened/resolved devfile

### ISSUE THREAD

**Issue by scottkurz** [openshift/odo#5112]
/kind bug

## What versions of software are you using?

**Operating System:** Win10

**Output of `odo version`:**   v2.3.1

## How did you run odo exactly?

1. Start with a `devfile.yaml` with a parent reference like:
```yaml
schemaVersion: 2.1.0
metadata:
  name: new-ol-version
  description: Child devfile to test OL image updating
parent:
  uri: "https://github.com/OpenLiberty/application-stack/releases/download/maven-0.7.0/devfile.yaml"
  components:
    - name: dev
      container:
        image: 'maven:3.6-adoptopenjdk-11-openj9'
```
2. `odo create mycomp`

## Actual behavior

My original devfile.yaml is completely replaced with a flattened devfile merging in the parent contents.  This is nice to see, but it might not be I want to store in Git / version control.

## Expected behavior

I'd expect to have some kind of option at least to flatten or not flatten.. or possibly something like the flattening would happen in a generated side file.
