### ISSUE TITLE
Externalize image's information needed by supervisord. odo push

### ISSUE THREAD

**Issue by cmoulliard** [openshift/odo#708]
As the commands needed to configure the supervisord like the path to copy the source, binary could be different between the different builder/s2i image, it is important to externalize such info using a configMap with by example this data model

```
images:
  - name: openjdk-1.8
    description: OpenJDK Java S2I Image
    registry: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
    version: 1.4-6
    parameters:
      - commands:
          - assemble: '/usr/local/s2i/assemble'
          - run: '/usr/local/s2i/run'
      - directory:
        - source: '/tmp/src/'
        - binary: '/deployments/'
```
